-- ============================================================================
-- AUTO-GENERATED — DO NOT EDIT
-- ============================================================================
-- Generated by scripts/generate-ddl.mjs from content/schemas/schema_pack_v0.8.json.
-- Per ARD-009: schema_pack is canonical; this file is a DERIVED ARTIFACT.
--
-- Schema version: 0.8.0
-- Generated at:   2026-05-21T21:59:04.677Z
--
-- To change DDL output:
--   1. Edit content/schemas/schema_pack_v0.8.json
--   2. Run `npm run gen:ddl`
--   3. Commit BOTH the schema change AND this regenerated file
--
-- Hand-authored migrations (NOT in this file):
--   - RLS policies — supabase/migrations/<ts>_rls_*.sql
--   - Realtime publications — supabase/migrations/<ts>_realtime_publications.sql
--   - Storage bucket policies — supabase/migrations/<ts>_storage_policies.sql
--   - Edge Function definitions — supabase/functions/<name>/index.ts
--
-- CI verifies via `npm run gen:check`.
-- Hand-edits will be overwritten.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Schema namespaces (per ARD-010)
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "public";
CREATE SCHEMA IF NOT EXISTS "content";
CREATE SCHEMA IF NOT EXISTS "state";
CREATE SCHEMA IF NOT EXISTS "behavior";
CREATE SCHEMA IF NOT EXISTS "engine";

-- ----------------------------------------------------------------------------
-- Native Postgres ENUM types (per ARD-011 §2)
-- ----------------------------------------------------------------------------
-- public.npc_closing_state
DO $$ BEGIN
  CREATE TYPE "public"."npc_closing_state" AS ENUM (
    'success_state',
    'passover_state',
    'death_state',
    'transfer_state',
    'special_state'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.want_model_kill_threshold
DO $$ BEGIN
  CREATE TYPE "public"."want_model_kill_threshold" AS ENUM (
    'warning',
    'danger',
    'critical',
    'absolute'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.want_model_target_class
DO $$ BEGIN
  CREATE TYPE "public"."want_model_target_class" AS ENUM (
    'individual',
    'institution',
    'concept',
    'self'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.knowledge_says_policy
DO $$ BEGIN
  CREATE TYPE "public"."knowledge_says_policy" AS ENUM (
    'open',
    'guarded',
    'selective',
    'silent'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.ambition_tick_cadence
DO $$ BEGIN
  CREATE TYPE "public"."ambition_tick_cadence" AS ENUM (
    'seasonal_4x_year',
    'monthly',
    'irregular_per_assignment',
    'liturgical_12x_year',
    'civic_6x_year',
    'trade_season_8x_year',
    'theological_irregular',
    'special'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.institution_schedule_tier
DO $$ BEGIN
  CREATE TYPE "public"."institution_schedule_tier" AS ENUM (
    'ngo_internal',
    'civic_weekly',
    'regional_seasonal',
    'cosmological_yearly'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.institution_baseline_unit
DO $$ BEGIN
  CREATE TYPE "public"."institution_baseline_unit" AS ENUM (
    'game_day',
    'game_week',
    'game_season',
    'game_year'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.internal_faction_alignment
DO $$ BEGIN
  CREATE TYPE "public"."internal_faction_alignment" AS ENUM (
    'loyal',
    'factional',
    'reformist',
    'schismatic'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.faction_tick_attempt_kind
DO $$ BEGIN
  CREATE TYPE "public"."faction_tick_attempt_kind" AS ENUM (
    'expansion',
    'consolidation',
    'defense',
    'withdrawal'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.faction_tick_outcome
DO $$ BEGIN
  CREATE TYPE "public"."faction_tick_outcome" AS ENUM (
    'gain',
    'stalemate',
    'setback'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.commodity_unit
DO $$ BEGIN
  CREATE TYPE "public"."commodity_unit" AS ENUM (
    'kg',
    'barrel',
    'ingot',
    'scrap',
    'bushel',
    'head'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.npc_memory_archetype
DO $$ BEGIN
  CREATE TYPE "public"."npc_memory_archetype" AS ENUM (
    'peasant',
    'soldier',
    'scholar',
    'devout',
    'magistrate',
    'broker',
    'aspirant_divine',
    'child',
    'contradiction_bearing'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.institutional_memory_archetype
DO $$ BEGIN
  CREATE TYPE "public"."institutional_memory_archetype" AS ENUM (
    'devout',
    'magistrate',
    'scholar',
    'broker'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.trade_route_active_status
DO $$ BEGIN
  CREATE TYPE "public"."trade_route_active_status" AS ENUM (
    'open',
    'disrupted',
    'closed'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- public.institution_response_resolution_kind
DO $$ BEGIN
  CREATE TYPE "public"."institution_response_resolution_kind" AS ENUM (
    'decisive',
    'deferred',
    'escalated',
    'ignored'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- PUBLIC schema — 43 entities
-- ============================================================================
-- campaign (public.campaign)
CREATE TABLE IF NOT EXISTS "public"."campaign" (
  "campaign_id" TEXT PRIMARY KEY NOT NULL,
  "mode" TEXT NOT NULL,
  "transparency_mode" TEXT,
  "ironman" BOOLEAN,
  "legacy_enabled" BOOLEAN,
  "current_time" JSONB NOT NULL  -- $ref: #/$defs/world_time,
  "current_region_id" TEXT,
  "active_character_id" TEXT NOT NULL,
  "world_seed" TEXT,
  "status" TEXT NOT NULL,
  "leveling_mode" TEXT,
  "regional_pack_pointers" JSONB,
  "active_pantheon_id" TEXT,
  "regional_currency_states" JSONB,
  "rng_lineage" JSONB,
  "party_state" JSONB,
  "former_party_members" JSONB,
  "session_log" JSONB,
  "accessibility_settings" JSONB,
  "ui_preference_state" JSONB,
  "world_pulse_recurring_events" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."campaign" ENABLE ROW LEVEL SECURITY;

-- player (public.player)
CREATE TABLE IF NOT EXISTS "public"."player" (
  "player_id" TEXT PRIMARY KEY NOT NULL,
  "identifier" TEXT NOT NULL,
  "form" TEXT NOT NULL,
  "knowledge_posture" TEXT,
  "first_perception" TEXT,
  "current_location" TEXT NOT NULL,
  "race_id" TEXT NOT NULL,
  "subrace_id" TEXT,
  "classes" JSONB NOT NULL,
  "level_total" SMALLINT NOT NULL,
  "experience" INTEGER,
  "proficiency_bonus" SMALLINT,
  "stats" JSONB NOT NULL  -- $ref: #/$defs/custom_stats_block,
  "derived_stats" JSONB NOT NULL  -- $ref: #/$defs/derived_stats_block,
  "meters" JSONB NOT NULL  -- $ref: #/$defs/meters_block,
  "hp" JSONB NOT NULL  -- $ref: #/$defs/hp_block,
  "hit_dice" JSONB,
  "armor_class" INTEGER,
  "speed_feet" INTEGER,
  "initiative_mod" JSONB  -- $ref: #/$defs/modifier,
  "skill_proficiencies" JSONB,
  "skill_expertise" JSONB,
  "save_proficiencies" JSONB,
  "languages" JSONB,
  "tool_proficiencies" JSONB,
  "alignment_descriptor" JSONB NOT NULL  -- $ref: #/$defs/alignment_descriptor,
  "traits" JSONB,
  "conditions" JSONB,
  "spell_slots" JSONB  -- $ref: #/$defs/spell_slot_table,
  "pact_slots" JSONB,
  "known_spells" JSONB,
  "spellbook_ids" JSONB,
  "concentration" JSONB,
  "abilities_known" JSONB,
  "abilities_hidden" JSONB,
  "inventory" JSONB,
  "attunement_slots" JSONB,
  "currency" JSONB  -- $ref: #/$defs/currency_amount,
  "carry_weight_kg" NUMERIC,
  "relationships" JSONB,
  "reputation_profile" JSONB,
  "faith_meters" JSONB,
  "path_ledger" JSONB,
  "canon_progression_ledger" JSONB,
  "pact_state" JSONB,
  "feats" JSONB,
  "inspiration_token" BOOLEAN,
  "body_modifications" JSONB  -- $ref: #/$defs/body_modifications_block,
  "death_state" JSONB,
  "body_modifications_block" JSONB  -- $ref: #/$defs/body_modifications_block,
  "knowledge_state" JSONB,
  "portrait_state" JSONB,
  "knowledge_posture_history" JSONB,
  "session_state" JSONB,
  "scrip_speculation_history" JSONB,
  "dream_state" JSONB,
  "legacy_inherited_substrate_weight" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("level_total" >= 1),
  CHECK ("level_total" <= 20),
  CHECK ("experience" >= 0),
  CHECK ("proficiency_bonus" >= 2),
  CHECK ("proficiency_bonus" <= 6),
  CHECK ("armor_class" >= 0),
  CHECK ("speed_feet" >= 0),
  CHECK ("carry_weight_kg" >= 0)
);
ALTER TABLE "public"."player" ENABLE ROW LEVEL SECURITY;

-- event (public.event)
CREATE TABLE IF NOT EXISTS "public"."event" (
  "event_id" TEXT PRIMARY KEY NOT NULL,
  "timestamp" JSONB NOT NULL  -- $ref: #/$defs/world_time,
  "event_type" TEXT NOT NULL,
  "kind" TEXT,
  "location_id" TEXT,
  "region_id" TEXT,
  "actors" JSONB,
  "cause_event_ids" JSONB,
  "truth" TEXT NOT NULL,
  "player_intent" TEXT,
  "visible_outcome" TEXT,
  "hidden_outcome" TEXT,
  "mechanics" JSONB,
  "affected_entities" JSONB,
  "affected_systems" JSONB NOT NULL,
  "severity" INTEGER,
  "visibility" INTEGER,
  "known_by_player" BOOLEAN,
  "known_by" JSONB,
  "rumors_created" JSONB,
  "beliefs_created" JSONB,
  "consequences_created" JSONB,
  "contradictions_created" JSONB,
  "canon_progression_credit" JSONB,
  "path_credits" JSONB,
  "party_member_witnesses" JSONB,
  "agent_provenance" JSONB,
  "combat_state" JSONB,
  "diegetic_elements" JSONB,
  "public_summary_for_ticker" TEXT,
  "scene_id" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."event" ENABLE ROW LEVEL SECURITY;

-- faction (public.faction)
CREATE TABLE IF NOT EXISTS "public"."faction" (
  "faction_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT,
  "region_id" TEXT,
  "core_goal" TEXT NOT NULL,
  "fear" TEXT,
  "resources" JSONB NOT NULL,
  "territory" JSONB,
  "leadership" JSONB,
  "internal_unity" INTEGER,
  "public_legitimacy" INTEGER,
  "player_awareness" INTEGER,
  "stance_to_player" TEXT NOT NULL,
  "fear_of_player" INTEGER,
  "trust_in_player" INTEGER,
  "dependency_on_player" INTEGER,
  "containment_priority" INTEGER,
  "active_plans" JSONB,
  "beliefs" JSONB,
  "faction_obligation_state_per_companion" JSONB,
  "scheduled_actions" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."faction" ENABLE ROW LEVEL SECURITY;

-- npc (public.npc)
CREATE TABLE IF NOT EXISTS "public"."npc" (
  "npc_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "race_id" TEXT,
  "faction_links" JSONB,
  "desire" TEXT NOT NULL,
  "fear" TEXT NOT NULL,
  "secret" TEXT,
  "resources" JSONB,
  "relationship_to_player" TEXT,
  "current_plan" TEXT NOT NULL,
  "next_action" TEXT,
  "betrayal_threshold" INTEGER,
  "loyalty_threshold" INTEGER,
  "corruption_exposure" INTEGER,
  "memory" JSONB,
  "stats_optional" JSONB  -- $ref: #/$defs/derived_stats_block,
  "hp_optional" JSONB  -- $ref: #/$defs/hp_block,
  "tracker_state" JSONB,
  "recruitable_via_bond" BOOLEAN,
  "recruitable_via_canon_event" TEXT,
  "behavior_tree_state" JSONB,
  "grudge_ledger" JSONB,
  "witness_history" JSONB,
  "want_model" JSONB NOT NULL  -- $ref: #/$defs/want_model,
  "knowledge_tri_layer" JSONB NOT NULL  -- $ref: #/$defs/knowledge_tri_layer,
  "closing_conditions" JSONB NOT NULL,
  "memory_archetype" "public"."npc_memory_archetype" NOT NULL,
  "ambition_tick" JSONB NOT NULL  -- $ref: #/$defs/ambition_tick,
  "schedule_nesting" JSONB NOT NULL  -- $ref: #/$defs/schedule_nesting,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."npc" ENABLE ROW LEVEL SECURITY;

-- rumor (public.rumor)
CREATE TABLE IF NOT EXISTS "public"."rumor" (
  "rumor_id" TEXT PRIMARY KEY NOT NULL,
  "source_event_id" TEXT NOT NULL,
  "current_claim" TEXT NOT NULL,
  "truth_accuracy" NUMERIC NOT NULL,
  "distortion_type" TEXT,
  "emotional_tone" TEXT,
  "spread_level" INTEGER,
  "regions_reached" JSONB,
  "factions_amplifying" JSONB,
  "factions_suppressing" JSONB,
  "versions" JSONB,
  "player_reputation_effect" JSONB,
  "status" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("truth_accuracy" >= 0),
  CHECK ("truth_accuracy" <= 1)
);
ALTER TABLE "public"."rumor" ENABLE ROW LEVEL SECURITY;

-- belief (public.belief)
CREATE TABLE IF NOT EXISTS "public"."belief" (
  "belief_id" TEXT PRIMARY KEY NOT NULL,
  "holder_type" TEXT NOT NULL,
  "holder_id" TEXT NOT NULL,
  "claim" TEXT NOT NULL,
  "truth_status" TEXT NOT NULL,
  "confidence" SMALLINT NOT NULL,
  "source_ids" JSONB,
  "emotional_charge" TEXT,
  "behavior_effects" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("confidence" >= 0),
  CHECK ("confidence" <= 100)
);
ALTER TABLE "public"."belief" ENABLE ROW LEVEL SECURITY;

-- consequence (public.consequence)
CREATE TABLE IF NOT EXISTS "public"."consequence" (
  "consequence_id" TEXT PRIMARY KEY NOT NULL,
  "source_event_id" TEXT NOT NULL,
  "trigger_type" TEXT NOT NULL,
  "trigger_value" TEXT,
  "effect_type" TEXT NOT NULL,
  "affected_entities" JSONB,
  "affected_systems" JSONB,
  "severity" INTEGER,
  "visibility_to_player" TEXT,
  "preventable" BOOLEAN,
  "status" TEXT NOT NULL,
  "resolution_options" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."consequence" ENABLE ROW LEVEL SECURITY;

-- state_diff (public.state_diff)
CREATE TABLE IF NOT EXISTS "public"."state_diff" (
  "state_diff_id" TEXT PRIMARY KEY NOT NULL,
  "source_event" TEXT NOT NULL,
  "approved" BOOLEAN NOT NULL,
  "approved_by" TEXT,
  "validator_chain_pass" JSONB,
  "changes" JSONB NOT NULL,
  "created_records" JSONB,
  "replay_seed" TEXT,
  "validator_chain_pass_detailed" JSONB,
  "dependency_event_ids" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."state_diff" ENABLE ROW LEVEL SECURITY;

-- contradiction_ledger_entry (public.contradiction_ledger_entry)
CREATE TABLE IF NOT EXISTS "public"."contradiction_ledger_entry" (
  "contradiction_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "source_event_id" TEXT NOT NULL,
  "previous_state_summary" TEXT,
  "new_state_summary" TEXT,
  "resolved" BOOLEAN NOT NULL,
  "resolution_event_id" TEXT,
  "surfacing_state" TEXT,
  "surface_after_day" INTEGER,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."contradiction_ledger_entry" ENABLE ROW LEVEL SECURITY;

-- class (public.class)
CREATE TABLE IF NOT EXISTS "public"."class" (
  "class_id" TEXT PRIMARY KEY NOT NULL,
  "default_calling_name" TEXT NOT NULL,
  "hit_die" TEXT NOT NULL,
  "primary_abilities" JSONB NOT NULL,
  "save_proficiencies" JSONB NOT NULL,
  "skill_choices" JSONB,
  "multiclass_prereq" JSONB,
  "custom_stat_hooks" JSONB,
  "spellcasting_kind" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."class" ENABLE ROW LEVEL SECURITY;

-- race (public.race)
CREATE TABLE IF NOT EXISTS "public"."race" (
  "race_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "ability_bonuses" JSONB NOT NULL,
  "size" TEXT NOT NULL,
  "speed_feet" INTEGER NOT NULL,
  "darkvision_feet" INTEGER,
  "languages_known" JSONB,
  "languages_choices" JSONB,
  "traits" JSONB,
  "subraces" JSONB,
  "world_mutation_state" TEXT,
  "custom_stat_tilt" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("speed_feet" >= 0),
  CHECK ("darkvision_feet" >= 0)
);
ALTER TABLE "public"."race" ENABLE ROW LEVEL SECURITY;

-- subrace (public.subrace)
CREATE TABLE IF NOT EXISTS "public"."subrace" (
  "subrace_id" TEXT PRIMARY KEY NOT NULL,
  "parent_race_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "ability_bonuses" JSONB,
  "extra_traits" JSONB,
  "world_mutation_state" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."subrace" ENABLE ROW LEVEL SECURITY;

-- deity (public.deity)
CREATE TABLE IF NOT EXISTS "public"."deity" (
  "deity_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "alternative_names" JSONB,
  "alignment" JSONB NOT NULL  -- $ref: #/$defs/alignment_descriptor,
  "domains" JSONB NOT NULL,
  "symbol" TEXT,
  "symbol_motif" TEXT,
  "notice_threshold_d100" SMALLINT,
  "origin" TEXT,
  "regional_origin_id" TEXT,
  "status" TEXT,
  "death_event_id" TEXT,
  "succession_rule" JSONB,
  "mythological_substrate_refs" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("notice_threshold_d100" >= 1),
  CHECK ("notice_threshold_d100" <= 100)
);
ALTER TABLE "public"."deity" ENABLE ROW LEVEL SECURITY;

-- pantheon (public.pantheon)
CREATE TABLE IF NOT EXISTS "public"."pantheon" (
  "pantheon_id" TEXT PRIMARY KEY NOT NULL,
  "origin_label" TEXT NOT NULL,
  "deity_ids" JSONB NOT NULL,
  "region_ids" JSONB,
  "status" TEXT,
  "mythological_substrate_refs" JSONB,
  "regional_configuration" JSONB,
  "faith_meter_negative_value_ui_treatment" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."pantheon" ENABLE ROW LEVEL SECURITY;

-- spell (public.spell)
CREATE TABLE IF NOT EXISTS "public"."spell" (
  "spell_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "level" SMALLINT NOT NULL,
  "school" TEXT NOT NULL,
  "regional_school_id" TEXT,
  "regional_origin_id" TEXT,
  "regional_pantheon_alignment" TEXT,
  "casting_time" TEXT NOT NULL,
  "range" TEXT NOT NULL,
  "components" JSONB NOT NULL,
  "duration" JSONB NOT NULL  -- $ref: #/$defs/duration_object,
  "concentration" BOOLEAN,
  "ritual_eligible" BOOLEAN,
  "save_type" TEXT,
  "attack_kind" TEXT,
  "damage_dice" TEXT,
  "damage_type" TEXT,
  "classes_allowed" JSONB NOT NULL,
  "domain_aligned" JSONB,
  "cost_layer" JSONB  -- $ref: #/$defs/spell_cost_layer,
  "description_template" TEXT,
  "tags" JSONB,
  "creates_canon_event_on_cast" BOOLEAN,
  "subschool" TEXT,
  "wild_twist" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("level" >= 0),
  CHECK ("level" <= 9)
);
ALTER TABLE "public"."spell" ENABLE ROW LEVEL SECURITY;

-- condition (public.condition)
CREATE TABLE IF NOT EXISTS "public"."condition" (
  "condition_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "source_pack" TEXT,
  "abbreviation" TEXT,
  "ui_glyph" TEXT NOT NULL,
  "ui_category" TEXT,
  "stackable" BOOLEAN,
  "level_based" BOOLEAN,
  "max_level" INTEGER,
  "duration_types_allowed" JSONB,
  "effect_rules" TEXT,
  "removal_methods" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("max_level" >= 1)
);
ALTER TABLE "public"."condition" ENABLE ROW LEVEL SECURITY;

-- item (public.item)
CREATE TABLE IF NOT EXISTS "public"."item" (
  "item_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "subtype" TEXT,
  "rarity" TEXT NOT NULL,
  "identification_dc" INTEGER,
  "identification_requires" JSONB,
  "attunement_required" BOOLEAN,
  "attunement_ceremony" TEXT,
  "weight_kg" NUMERIC,
  "value_cp" INTEGER,
  "value_currency_alt" JSONB  -- $ref: #/$defs/currency_amount,
  "equip_slot" TEXT,
  "tinting_class" TEXT,
  "bound_to_you" BOOLEAN,
  "regional_origin_id" TEXT,
  "damage_dice" TEXT,
  "damage_type" TEXT,
  "weapon_properties" JSONB,
  "armor_ac_base" INTEGER,
  "armor_dex_cap" INTEGER,
  "armor_strength_min" INTEGER,
  "armor_stealth_disadvantage" BOOLEAN,
  "effects_on_equip" JSONB,
  "effects_on_attune" JSONB,
  "effects_on_use" JSONB,
  "charges" JSONB,
  "curse_kind" TEXT,
  "deicidal" BOOLEAN,
  "soul_template" JSONB,
  "memory_template" JSONB,
  "transformable_hooks" JSONB,
  "effects_on_attune_structured" JSONB,
  "effects_on_equip_structured" JSONB,
  "effects_on_use_structured" JSONB,
  "witness_payload" JSONB,
  "adaptagen_kind" TEXT,
  "adaptagen_duration_hours" INTEGER,
  "adaptagen_effect_payload" JSONB,
  "evolution_ledger" JSONB,
  "description_long" TEXT,
  "description_short" TEXT,
  "effects_passive_structured" JSONB,
  "stackable" BOOLEAN,
  "stack_size_max" INTEGER,
  "requires_attunement" BOOLEAN,
  "intermediate_for_recipe_ids" JSONB,
  "is_intermediate" BOOLEAN,
  "notes" TEXT,
  "regional_pack_id" TEXT,
  "attunement_slot_cost" SMALLINT,
  "weight_lb" NUMERIC,
  "value_in_scrip" INTEGER,
  "value_note" TEXT,
  "tags" JSONB,
  "crafting" JSONB,
  "acquisition_method" TEXT,
  "charges_max" INTEGER,
  "charges_recover" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("identification_dc" >= 0),
  CHECK ("weight_kg" >= 0),
  CHECK ("value_cp" >= 0),
  CHECK ("stack_size_max" >= 1),
  CHECK ("attunement_slot_cost" >= 0),
  CHECK ("attunement_slot_cost" <= 3),
  CHECK ("weight_lb" >= 0),
  CHECK ("value_in_scrip" >= 0),
  CHECK ("charges_max" >= 0)
);
ALTER TABLE "public"."item" ENABLE ROW LEVEL SECURITY;

-- recipe (public.recipe)
CREATE TABLE IF NOT EXISTS "public"."recipe" (
  "recipe_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "track" TEXT,
  "tool_required" TEXT,
  "station_required" TEXT,
  "ingredients" JSONB,
  "output_item_id" TEXT,
  "output_quantity" INTEGER,
  "workday_cost" NUMERIC,
  "gp_cost" NUMERIC,
  "difficulty_dc" INTEGER,
  "ability_check" TEXT,
  "regional_origin_id" TEXT,
  "branching_outcomes" TEXT,
  "witness_inheritance" TEXT,
  "invisible_work" TEXT,
  "station_alternative_routes" JSONB,
  "materials" JSONB NOT NULL,
  "produces_item_id" TEXT NOT NULL,
  "primary_station_id" TEXT,
  "alternative_station_ids" JSONB,
  "time_in_world_hours" TEXT,
  "tags" JSONB,
  "craft_track" TEXT,
  "skill_check" TEXT,
  "dc" SMALLINT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("output_quantity" >= 1),
  CHECK ("workday_cost" >= 0),
  CHECK ("gp_cost" >= 0),
  CHECK ("difficulty_dc" >= 0),
  CHECK ("time_in_world_hours" >= 0),
  CHECK ("dc" >= 1),
  CHECK ("dc" <= 40)
);
ALTER TABLE "public"."recipe" ENABLE ROW LEVEL SECURITY;

-- region (public.region)
CREATE TABLE IF NOT EXISTS "public"."region" (
  "region_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "framing_notes" TEXT,
  "regional_pack_refs" JSONB,
  "active_pantheon_id" TEXT,
  "active_pantheon_config_id" TEXT,
  "currency_pack_id" TEXT,
  "conditions_pack_id" TEXT,
  "magic_traditions_pack_id" TEXT,
  "cult_institution_refs" JSONB,
  "heretical_reading_pattern_refs" JSONB,
  "substrate_exposed_refs" JSONB,
  "weather_state" JSONB,
  "weather_history" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."region" ENABLE ROW LEVEL SECURITY;

-- regional_pack (public.regional_pack)
CREATE TABLE IF NOT EXISTS "public"."regional_pack" (
  "pack_id" TEXT NOT NULL,
  "region_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "version" TEXT,
  "contents_path" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."regional_pack" ENABLE ROW LEVEL SECURITY;

-- mythological_substrate_entry (public.mythological_substrate_entry)
CREATE TABLE IF NOT EXISTS "public"."mythological_substrate_entry" (
  "substrate_id" TEXT NOT NULL,
  "name_descriptor" TEXT,
  "kind" TEXT NOT NULL,
  "era_band" JSONB,
  "status" TEXT NOT NULL,
  "patterns_invoked" JSONB,
  "fragments_known" JSONB,
  "active_deity_readings" JSONB,
  "exposure_method" JSONB,
  "world_impact_if_exposed" TEXT,
  "min_exposure_cooldown_days" INTEGER,
  "drawn_from" TEXT,
  "what_we_did_not_take" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("min_exposure_cooldown_days" >= 0)
);
ALTER TABLE "public"."mythological_substrate_entry" ENABLE ROW LEVEL SECURITY;

-- loot_table (public.loot_table)
CREATE TABLE IF NOT EXISTS "public"."loot_table" (
  "loot_table_id" TEXT PRIMARY KEY NOT NULL,
  "scope" TEXT NOT NULL,
  "trigger_event_kind" TEXT NOT NULL,
  "region_id" TEXT,
  "location_id" TEXT,
  "faction_id" TEXT,
  "rolls" JSONB NOT NULL,
  "refusal_consequences" JSONB,
  "template_grammar_version" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."loot_table" ENABLE ROW LEVEL SECURITY;

-- material (public.material)
CREATE TABLE IF NOT EXISTS "public"."material" (
  "material_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "tinting_class" TEXT,
  "regional_origin_id" TEXT,
  "weight_kg_per_unit" NUMERIC,
  "value_cp_per_unit" INTEGER,
  "witness_payload" TEXT,
  "tier" TEXT,
  "slice_eligible" BOOLEAN,
  "is_intermediate" BOOLEAN,
  "sourcing_geography" JSONB,
  "decay_states" JSONB,
  "craft_tracks_eligible" JSONB,
  "acquisition_method" TEXT,
  "notes" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("weight_kg_per_unit" >= 0),
  CHECK ("value_cp_per_unit" >= 0)
);
ALTER TABLE "public"."material" ENABLE ROW LEVEL SECURITY;

-- regional_currency_state (public.regional_currency_state)
CREATE TABLE IF NOT EXISTS "public"."regional_currency_state" (
  "currency_id" TEXT NOT NULL,
  "region_id" TEXT NOT NULL,
  "base_value_gp" NUMERIC NOT NULL,
  "volatility_modifier" NUMERIC NOT NULL,
  "crisis_intensity_modifier" TEXT NOT NULL,
  "crisis_label" TEXT,
  "last_recompute_event_id" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("base_value_gp" >= 0),
  CHECK ("volatility_modifier" >= 0.5),
  CHECK ("volatility_modifier" <= 2)
);
ALTER TABLE "public"."regional_currency_state" ENABLE ROW LEVEL SECURITY;

-- cult_institution (public.cult_institution)
CREATE TABLE IF NOT EXISTS "public"."cult_institution" (
  "cult_institution_id" TEXT PRIMARY KEY NOT NULL,
  "faction_id" TEXT NOT NULL,
  "region_id" TEXT NOT NULL,
  "primary_deity_ids" JSONB,
  "clerical_archetype" TEXT,
  "doctrines" JSONB,
  "taboos" JSONB,
  "rite_kinds" JSONB,
  "heretical_figures" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."cult_institution" ENABLE ROW LEVEL SECURITY;

-- creature_material (public.creature_material)
CREATE TABLE IF NOT EXISTS "public"."creature_material" (
  "creature_material_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "source_creature_kinds" JSONB NOT NULL,
  "harvest_kind" TEXT NOT NULL,
  "yield_per_creature" JSONB,
  "harvest_dc" INTEGER,
  "harvest_skill" TEXT,
  "preservation_required" BOOLEAN,
  "preservation_method" TEXT,
  "value_cp_per_unit" INTEGER,
  "witness_payload" JSONB,
  "tier" TEXT,
  "craft_tracks_eligible" JSONB,
  "decay_states" JSONB,
  "regional_pack_id" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."creature_material" ENABLE ROW LEVEL SECURITY;

-- material_substitution (public.material_substitution)
CREATE TABLE IF NOT EXISTS "public"."material_substitution" (
  "substitution_id" TEXT NOT NULL,
  "recipe_id" TEXT NOT NULL,
  "primary_material_id" TEXT NOT NULL,
  "alternative_material_id" TEXT NOT NULL,
  "dc_modifier" INTEGER,
  "yield_modifier" NUMERIC,
  "narrative_tag" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."material_substitution" ENABLE ROW LEVEL SECURITY;

-- companion (public.companion)
CREATE TABLE IF NOT EXISTS "public"."companion" (
  "companion_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "underlying_npc_id" TEXT NOT NULL,
  "recruitment_path" TEXT NOT NULL,
  "recruited_on_day" INTEGER NOT NULL,
  "recruited_event_id" TEXT,
  "terms" JSONB,
  "autonomous_drivers" JSONB,
  "party_tier_state" TEXT,
  "witnessed_event_ids" JSONB,
  "canon_progression_credit" JSONB,
  "stats_block" JSONB,
  "inventory" JSONB,
  "hp_block" JSONB  -- $ref: #/$defs/hp_block,
  "meters_block" JSONB  -- $ref: #/$defs/meters_block,
  "conditions_active" JSONB,
  "is_dead" BOOLEAN,
  "death_state" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."companion" ENABLE ROW LEVEL SECURITY;

-- orchestrator_session (public.orchestrator_session)
CREATE TABLE IF NOT EXISTS "public"."orchestrator_session" (
  "session_id" TEXT NOT NULL,
  "campaign_id" TEXT NOT NULL,
  "player_user_id" TEXT,
  "session_start_at" TIMESTAMPTZ,
  "session_end_at" TIMESTAMPTZ,
  "rng_seed" TEXT NOT NULL,
  "rng_stream_position" INTEGER,
  "agent_call_log" JSONB,
  "active" BOOLEAN,
  "last_state_diff_id" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."orchestrator_session" ENABLE ROW LEVEL SECURITY;

-- agent_envelope (public.agent_envelope)
CREATE TABLE IF NOT EXISTS "public"."agent_envelope" (
  "envelope_id" TEXT NOT NULL,
  "session_id" TEXT NOT NULL,
  "agent_name" TEXT NOT NULL,
  "stage_index" SMALLINT NOT NULL,
  "input_payload" JSONB,
  "output_payload" JSONB,
  "validator_pass" BOOLEAN,
  "called_at" TIMESTAMPTZ,
  "completed_at" TIMESTAMPTZ,
  "error" TEXT,
  "model_id" TEXT,
  "tokens_in" INTEGER,
  "tokens_out" INTEGER,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("stage_index" >= 1),
  CHECK ("stage_index" <= 6)
);
ALTER TABLE "public"."agent_envelope" ENABLE ROW LEVEL SECURITY;

-- quirk (public.quirk)
CREATE TABLE IF NOT EXISTS "public"."quirk" (
  "quirk_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "description_template" TEXT NOT NULL,
  "behavioral_modifier" JSONB,
  "intensity" SMALLINT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("intensity" >= 1),
  CHECK ("intensity" <= 5)
);
ALTER TABLE "public"."quirk" ENABLE ROW LEVEL SECURITY;

-- recruitment_quest (public.recruitment_quest)
CREATE TABLE IF NOT EXISTS "public"."recruitment_quest" (
  "quest_id" TEXT NOT NULL,
  "target_companion_id" TEXT NOT NULL,
  "stages" JSONB,
  "completion_offer" JSONB,
  "abandonment_consequences" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."recruitment_quest" ENABLE ROW LEVEL SECURITY;

-- location (public.location)
CREATE TABLE IF NOT EXISTS "public"."location" (
  "location_id" TEXT PRIMARY KEY NOT NULL,
  "region_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "discovered_by_player_event_id" TEXT,
  "fog_of_knowledge_state" TEXT,
  "parent_location_id" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."location" ENABLE ROW LEVEL SECURITY;

-- travel_route (public.travel_route)
CREATE TABLE IF NOT EXISTS "public"."travel_route" (
  "route_id" TEXT NOT NULL,
  "from_location_id" TEXT NOT NULL,
  "to_location_id" TEXT NOT NULL,
  "traversal_cost_hours" INTEGER,
  "traversal_risk" TEXT,
  "knowledge_required" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."travel_route" ENABLE ROW LEVEL SECURITY;

-- conflict_envelope (public.conflict_envelope)
CREATE TABLE IF NOT EXISTS "public"."conflict_envelope" (
  "envelope_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "parties" JSONB NOT NULL,
  "stakes" TEXT,
  "resolution_path" TEXT,
  "kind_specific_fields" JSONB,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."conflict_envelope" ENABLE ROW LEVEL SECURITY;

-- portrait_layer_definition (public.portrait_layer_definition)
CREATE TABLE IF NOT EXISTS "public"."portrait_layer_definition" (
  "layer_id" TEXT NOT NULL,
  "layer_kind" TEXT NOT NULL,
  "svg_path" TEXT NOT NULL,
  "triggered_by" JSONB,
  "anchor_point" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."portrait_layer_definition" ENABLE ROW LEVEL SECURITY;

-- imposed_spell (public.imposed_spell)
CREATE TABLE IF NOT EXISTS "public"."imposed_spell" (
  "spell_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "level" SMALLINT NOT NULL,
  "school" TEXT NOT NULL,
  "regional_school_id" TEXT NOT NULL,
  "regional_origin_id" TEXT NOT NULL,
  "regional_pantheon_alignment" TEXT,
  "casting_time" TEXT NOT NULL,
  "range" TEXT NOT NULL,
  "components" JSONB NOT NULL,
  "duration" JSONB NOT NULL  -- $ref: #/$defs/duration_object,
  "concentration" BOOLEAN,
  "ritual_eligible" BOOLEAN,
  "save_type" TEXT,
  "attack_kind" TEXT,
  "damage_dice" TEXT,
  "damage_type" TEXT,
  "classes_allowed" JSONB NOT NULL,
  "domain_aligned" JSONB,
  "cost_layer" JSONB  -- $ref: #/$defs/spell_cost_layer,
  "description_template" TEXT,
  "tags" JSONB,
  "creates_canon_event_on_cast" BOOLEAN,
  "subschool" TEXT,
  "wild_twist" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("level" >= 0),
  CHECK ("level" <= 9)
);
ALTER TABLE "public"."imposed_spell" ENABLE ROW LEVEL SECURITY;

-- litany (public.litany)
CREATE TABLE IF NOT EXISTS "public"."litany" (
  "litany_id" TEXT PRIMARY KEY NOT NULL,
  "title" TEXT NOT NULL,
  "text_body" TEXT NOT NULL,
  "mechanical_effect" TEXT,
  "voice_register" TEXT,
  "rite_kind" TEXT,
  "faction_origin" TEXT,
  "first_heard_default_npc" TEXT,
  "origin_institution" TEXT,
  "canonical_use" TEXT,
  "tags" JSONB,
  "tone_tags" JSONB,
  "regional_origin_id" TEXT,
  "schema_version" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."litany" ENABLE ROW LEVEL SECURITY;

-- marginalia (public.marginalia)
CREATE TABLE IF NOT EXISTS "public"."marginalia" (
  "marginalia_id" TEXT PRIMARY KEY NOT NULL,
  "text" TEXT NOT NULL,
  "trigger_kind" TEXT,
  "trigger_event_kind" TEXT,
  "trigger_condition" TEXT,
  "display_context" TEXT,
  "tone_tags" JSONB,
  "regional_origin_id" TEXT,
  "schema_version" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "public"."marginalia" ENABLE ROW LEVEL SECURITY;

-- opex_state (public.opex_state)
CREATE TABLE IF NOT EXISTS "public"."opex_state" (
  "utc_date" TEXT NOT NULL,
  "daily_spend_usd" NUMERIC NOT NULL,
  "daily_cap_usd" NUMERIC NOT NULL,
  "session_budgets" JSONB,
  "last_updated_iso" TEXT,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("daily_spend_usd" >= 0),
  CHECK ("daily_cap_usd" >= 0)
);
ALTER TABLE "public"."opex_state" ENABLE ROW LEVEL SECURITY;

-- opex_event (public.opex_event)
CREATE TABLE IF NOT EXISTS "public"."opex_event" (
  "event_id" TEXT NOT NULL,
  "timestamp_iso" TEXT NOT NULL,
  "agent" TEXT NOT NULL,
  "model_id" TEXT NOT NULL,
  "tier" TEXT NOT NULL,
  "tokens_in" INTEGER NOT NULL,
  "tokens_out" INTEGER NOT NULL,
  "est_cost_usd" NUMERIC NOT NULL,
  "fallback_reason" TEXT,
  "success" BOOLEAN NOT NULL,
  "error_kind" TEXT,
  "session_id" TEXT,
  "latency_ms" INTEGER,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("tokens_in" >= 0),
  CHECK ("tokens_out" >= 0),
  CHECK ("est_cost_usd" >= 0),
  CHECK ("latency_ms" >= 0)
);
ALTER TABLE "public"."opex_event" ENABLE ROW LEVEL SECURITY;

-- model_tier_policy (public.model_tier_policy)
CREATE TABLE IF NOT EXISTS "public"."model_tier_policy" (
  "policy_id" TEXT NOT NULL,
  "version" TEXT,
  "last_updated_iso" TEXT,
  "daily_cap_usd" NUMERIC,
  "per_session_token_budget" INTEGER,
  "agent_tiers" JSONB NOT NULL,
  "fallback_chains" JSONB NOT NULL,
  "max_fallback_attempts" SMALLINT,
  "cap_buffer_pct" NUMERIC,
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("daily_cap_usd" >= 0),
  CHECK ("per_session_token_budget" >= 0),
  CHECK ("max_fallback_attempts" >= 1),
  CHECK ("max_fallback_attempts" <= 5),
  CHECK ("cap_buffer_pct" >= 0),
  CHECK ("cap_buffer_pct" <= 0.5)
);
ALTER TABLE "public"."model_tier_policy" ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- CONTENT schema — 2 entities
-- ============================================================================
-- institution (content.institution)
-- Phase 24b §4.3 / Bundle B — Institution entity. Distinct from FactionSchema: faction-level orgs may or may not be institutions (e.g. Drowned Church is both; a feud-clan is a faction but not an institution). Institutions have cadence, jurisdictional strength, internal sub-factions, and an institutional memory archetype. Source: Sec L.II.
CREATE TABLE IF NOT EXISTS "content"."institution" (
  "institution_id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "tags" JSONB,
  "institution_cadence" JSONB NOT NULL  -- $ref: #/$defs/institution_cadence,
  "jurisdictional_strength" SMALLINT NOT NULL,
  "internal_factions" JSONB NOT NULL,
  "institutional_memory_archetype" "content"."institutional_memory_archetype" NOT NULL,
  "parent_faction_id" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ("jurisdictional_strength" >= 0),
  CHECK ("jurisdictional_strength" <= 100),
  FOREIGN KEY ("parent_faction_id") REFERENCES "content"."faction"(id) ON DELETE SET NULL
);
COMMENT ON TABLE "content"."institution" IS "Phase 24b §4.3 / Bundle B — Institution entity. Distinct from FactionSchema: faction-level orgs may or may not be institutions (e.g. Drowned Church is both; a feud-clan is a faction but not an institution). Institutions have cadence, jurisdictional strength, internal sub-factions, and an institutional memory archetype. Source: Sec L.II.";
ALTER TABLE "content"."institution" ENABLE ROW LEVEL SECURITY;

-- trade_route_v08 (content.trade_route_v08)
-- Phase 24b §4.4 / Bundle C / L.III-SC-06 — Commerce route distinct from v0.7 geographic travel_route $def. Carries commodity + capacity + controlling faction + active status. Reconciled with v0.7 travel_route via engine adapter at scene-load boundary.
CREATE TABLE IF NOT EXISTS "content"."trade_route_v08" (
  "route_id" TEXT NOT NULL,
  "origin_location_id" TEXT NOT NULL,
  "destination_location_id" TEXT NOT NULL,
  "commodity_id" TEXT NOT NULL,
  "controlling_faction_id" TEXT,
  "weather_dependency" BOOLEAN NOT NULL,
  "active_status" "content"."trade_route_active_status" NOT NULL,
  "capacity_per_season" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("origin_location_id") REFERENCES "content"."location"(id) ON DELETE RESTRICT,
  FOREIGN KEY ("destination_location_id") REFERENCES "content"."location"(id) ON DELETE RESTRICT,
  FOREIGN KEY ("controlling_faction_id") REFERENCES "content"."faction"(id) ON DELETE SET NULL,
  CHECK ("capacity_per_season" >= 0)
);
COMMENT ON TABLE "content"."trade_route_v08" IS "Phase 24b §4.4 / Bundle C / L.III-SC-06 — Commerce route distinct from v0.7 geographic travel_route $def. Carries commodity + capacity + controlling faction + active status. Reconciled with v0.7 travel_route via engine adapter at scene-load boundary.";
ALTER TABLE "content"."trade_route_v08" ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STATE schema — 1 entities
-- ============================================================================
-- institution_response_queue_entry (state.institution_response_queue_entry)
-- Phase 24b §4.3 / Bundle B / L.II-SC-02 — Per-event entry in an institution's response queue. Lives in state.* schema (per ARD-010; mutable runtime queue). Engine writes entries when triggering events fire; resolves by NPC actions or institutional default policy.
CREATE TABLE IF NOT EXISTS "state"."institution_response_queue_entry" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "institution_id" TEXT NOT NULL,
  "trigger_event_id" TEXT NOT NULL,
  "proposed_response" TEXT NOT NULL,
  "decision_window" JSONB NOT NULL,
  "resolved_by_npc_ids" JSONB,
  "resolution_kind" "state"."institution_response_resolution_kind",
  "schema_version" TEXT NOT NULL DEFAULT 'v0.8',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("institution_id") REFERENCES "state"."institution"(id) ON DELETE CASCADE
);
COMMENT ON TABLE "state"."institution_response_queue_entry" IS "Phase 24b §4.3 / Bundle B / L.II-SC-02 — Per-event entry in an institution's response queue. Lives in state.* schema (per ARD-010; mutable runtime queue). Engine writes entries when triggering events fire; resolves by NPC actions or institutional default policy.";
ALTER TABLE "state"."institution_response_queue_entry" ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- END OF GENERATED DDL
-- 46 entities · 15 enums · 5 schemas
-- ----------------------------------------------------------------------------