/**
 * ============================================================================
 * AUTO-GENERATED — DO NOT EDIT
 * ============================================================================
 * Generated by scripts/generate-types.mjs from the latest content/schemas/schema_pack_vX.X.json.
 *
 * To change a shape:
 *   1. Edit the latest content/schemas/schema_pack_vX.X.json
 *   2. Run `npm run gen:types`
 *   3. Commit BOTH the schema change AND this regenerated file
 *
 * CI verifies via `npm run gen:types:check`.
 * Hand-edits will be overwritten.
 * ============================================================================
 */

/* eslint-disable */
// prettier-ignore

export type AbilityScore = number;
export type BoundedInt_0_10 = number;
export type Modifier = number;
export type AlignmentDescriptor = "LG" | "NG" | "CG" | "LN" | "N" | "CN" | "LE" | "NE" | "CE";
export type DurationObject =
  | {
      kind?: "instant";
    }
  | {
      kind?: "n_turns";
      n: number;
    }
  | {
      kind?: "n_scenes";
      n: number;
    }
  | {
      kind?: "until_long_rest";
    }
  | {
      kind?: "until_short_rest";
    }
  | {
      kind?: "until_canon_event";
      event_id: string;
    }
  | {
      kind?: "permanent";
    }
  | {
      kind?: "concentration";
      max_minutes?: number;
    };
export type BoundedIntNeg10Pos10 = number;

/**
 * Composite — emits one interface per entity. Per-entity aliases at bottom.
 */
export interface FirstPerceptionSchemaPack {
  campaign?: {
    campaign_id: string;
    mode: "standard" | "immersive" | "tactical" | "hardcore" | "creator_debug";
    transparency_mode?: string;
    ironman?: boolean;
    legacy_enabled?: boolean;
    current_time: WorldTime;
    current_region_id?: string;
    active_character_id: string;
    world_seed?: string;
    status: "active" | "dead" | "legacy" | "ended";
    leveling_mode?: "xp" | "milestone";
    regional_pack_pointers?: RegionalPackRef[];
    active_pantheon_id?: string;
    regional_currency_states?: string[];
    rng_lineage?: {
      root_seed?: string;
      stream_count?: number;
      last_committed_event_id?: string;
    };
    /**
     * R-132-P: top-level party tracking. 4-max party (1 player + up to 3 companions).
     */
    party_state?: {
      slot_count?: number;
      slots?: {
        slot_index?: number;
        companion_id?: string | null;
        joined_event_id?: string | null;
        joined_day?: number | null;
        active?: boolean;
      }[];
      former_members?: {}[];
    };
    /**
     * R-148-P: persistent post-departure state for companions who left the party.
     */
    former_party_members?: {
      companion_id?: string;
      departed_day?: number;
      departure_kind?:
        | "dismissed"
        | "betrayed"
        | "died"
        | "recalled_by_faction"
        | "departed_X12"
        | "departed_X13"
        | "departed_X14"
        | "departed_X15"
        | "departed_X16"
        | "obligation_expired";
      departure_event_id?: string;
      post_departure_state?: {} | null;
    }[];
    /**
     * R-97-B: ordered session_ids that have committed against this campaign. Multi-session replay support.
     */
    session_log?: string[];
    /**
     * R-116-D: slice accessibility commitments.
     */
    accessibility_settings?: {
      reduced_motion?: boolean;
      screen_reader_mode?: boolean;
      color_blind_palette_id?: null | "deuteranopia" | "protanopia" | "tritanopia";
      high_contrast?: boolean;
      adaptive_prose_density?: "compact" | "standard" | "expanded";
    };
    /**
     * R-117-D: persistent UI prefs. Closes R-62.
     */
    ui_preference_state?: {
      /**
       * R-62 closure: per-tab collapse preferences at 1366×768
       */
      tab_grouping_1366?: {};
      hotbar_order?: string[];
      tooltip_density?: "minimal" | "standard" | "verbose";
      preferred_default_sheet_tab?: string;
    };
    /**
     * R-127-F (speculative): scheduled events that fire on a cadence (e.g., weekly salt vigil) outside the agent loop.
     */
    world_pulse_recurring_events?: {
      recurring_event_id?: string;
      event_kind?: string;
      cadence_days?: number;
      first_fired_day?: number;
      next_fires_day?: number;
    }[];
  };
  player?: {
    player_id: string;
    identifier: string;
    form: string;
    knowledge_posture?: string;
    first_perception?: string;
    current_location: string;
    race_id: string;
    subrace_id?: string | null;
    /**
     * @minItems 1
     */
    classes: [
      {
        class_id: string;
        level: number;
        subclass_id?: string | null;
        is_pact_class?: boolean;
      },
      ...{
        class_id: string;
        level: number;
        subclass_id?: string | null;
        is_pact_class?: boolean;
      }[]
    ];
    level_total: number;
    experience?: number;
    proficiency_bonus?: number;
    stats: CustomStatsBlock;
    derived_stats: DerivedStatsBlock;
    meters: MetersBlock;
    hp: HpBlock;
    hit_dice?: HitDiceEntry[];
    armor_class?: number;
    speed_feet?: number;
    initiative_mod?: Modifier;
    skill_proficiencies?: string[];
    skill_expertise?: string[];
    save_proficiencies?: ("str" | "dex" | "con" | "int" | "wis" | "cha")[];
    languages?: string[];
    tool_proficiencies?: string[];
    alignment_descriptor: AlignmentDescriptor;
    traits?: {}[];
    conditions?: ConditionActiveInstance[];
    spell_slots?: SpellSlotTable;
    pact_slots?: {
      max?: number;
      current?: number;
      slot_level?: number;
    };
    known_spells?: KnownSpellEntry[];
    spellbook_ids?: string[];
    concentration?: {
      active_spell_id?: string | null;
      started_at?: WorldTime;
    };
    abilities_known?: unknown[];
    abilities_hidden?: unknown[];
    inventory?: InventoryEntry[];
    /**
     * @minItems 3
     * @maxItems 3
     */
    attunement_slots?: [AttunementSlot, AttunementSlot, AttunementSlot];
    currency?: CurrencyAmount;
    carry_weight_kg?: number;
    relationships?: {};
    reputation_profile?: {
      per_faction?: {
        [k: string]: BoundedIntNeg10Pos10;
      };
      per_region?: {
        [k: string]: BoundedIntNeg10Pos10;
      };
      notoriety?: number;
    };
    faith_meters?: FaithMeterEntry[];
    path_ledger?: PathLedgerEntry[];
    /**
     * @minItems 3
     * @maxItems 3
     */
    canon_progression_ledger?: [CanonProgressionEntry, CanonProgressionEntry, CanonProgressionEntry];
    pact_state?: {
      patron_id?: string;
      pact_kind?: string;
      debt_floor?: number;
      active_pact_clauses?: string[];
      resolution_required_before_multiclass_out?: boolean;
    };
    feats?: string[];
    inspiration_token?: boolean;
    body_modifications?: BodyModificationsBlock;
    death_state?: {
      is_dead?: boolean;
      death_day?: number | null;
      death_event_id?: string | null;
      ending_kind?:
        | null
        | "physical_death"
        | "X12_apotheosis"
        | "X13_unmaking"
        | "X14_withdrawal"
        | "X15_pact_collection"
        | "X16_corruption_transformation";
      /**
       * R-88-A: Narrator-generated terminal text (postcard-shaped). Per Narrator Form-of-Ending prompt. Persisted for Death/Legacy screen rendering.
       */
      form_of_ending_narration?: string | null;
    } | null;
    body_modifications_block?: BodyModificationsBlock1;
    knowledge_state?: {
      /**
       * R-107-C: per-location knowledge map (deferred bundle: exploration_system)
       */
      locations_known?: {
        [k: string]: {
          fog_state?: "unknown" | "glimpsed" | "visited" | "known";
          first_seen_event_id?: string | null;
        };
      };
      facts_known?: unknown[];
      rumors_heard?: unknown[];
    };
    /**
     * R-111-D: Portrait System state per FDR Part 1.5 spec.
     */
    portrait_state?: {
      procedural_layers?: {
        race_silhouette?: string;
        class_glyph?: string;
        alignment_tint?: string;
        condition_overlay?: string[];
        body_mod_overlay?: string[];
        meter_overlay?: {};
        tilt?: number;
      };
      /**
       * References to portrait_layer_definition entries
       */
      curated_overlays?: string[];
      /**
       * AI-generated cosmetic image path (set at character creation)
       */
      ai_cosmetic_slot?: string | null;
    };
    /**
     * R-115-D: posture switches over time; affects achievement eligibility per v0.1 Ch V.
     */
    knowledge_posture_history?: {
      posture?: "mechanical" | "interpretive" | "performative" | "credulous" | "skeptical";
      switched_on_day?: number;
      switched_event_id?: string;
      switched_by?: "player_explicit" | "consequence" | "narrative_trigger";
    }[];
    /**
     * Transient session state on player; cleared on session boundary.
     */
    session_state?: {
      /**
       * R-119-E: per Glance Bar mechanism (FDR Part 2.3)
       */
      last_main_scene_focus_at?: string | null;
      current_session_id?: string | null;
      transient_flags?: {};
    };
    /**
     * R-124-E: speculative-profit tracking for R-65 (scrip speculation cap at 25% gain).
     */
    scrip_speculation_history?: {
      speculation_id?: string;
      scrip_kind?: string;
      bought_at_rate?: number;
      sold_at_rate?: number | null;
      profit_loss_cp?: number;
      day?: number;
    }[];
    /**
     * R-128-F (speculative): a separate substrate where dream-region content could play. v0.3 framing.
     */
    dream_state?: {
      dream_substrate_id?: string;
      last_dreamt_day?: number;
      dream_canon_progression_credit?: {};
      dream_witnessed_events?: unknown[];
    } | null;
    /**
     * R-131-F (speculative): per-substrate weight inherited from prior characters. Per X.12/X.16 legacy seeding; multi-character campaign play.
     */
    legacy_inherited_substrate_weight?: {
      [k: string]: number;
    } | null;
  };
  event?: {
    event_id: string;
    timestamp: WorldTime;
    event_type: string;
    kind?:
      | "physical_conflict"
      | "social_conflict"
      | "faith_conflict"
      | "economic_conflict"
      | "memory_conflict"
      | "reality_pressure"
      | "discovery"
      | "transformation"
      | "deicide"
      | "deity_birth"
      | "regional_apostasy"
      | "substrate_exposure"
      | "rite"
      | "oath_made"
      | "oath_broken"
      | "oath_fulfilled"
      | "craft"
      | "salvage"
      | "loot_taken"
      | "loot_refused"
      | "notice_convergence"
      | "other"
      | "notice_threshold_cross"
      | "body_modification_applied"
      | "body_modification_removed"
      | "adaptagen_consumed"
      | "mutation_canon_event";
    location_id?: string;
    region_id?: string;
    actors?: unknown[];
    cause_event_ids?: unknown[];
    truth: string;
    player_intent?: string;
    visible_outcome?: string;
    hidden_outcome?: string;
    mechanics?: {};
    affected_entities?: unknown[];
    affected_systems: unknown[];
    severity?: number;
    visibility?: number;
    known_by_player?: boolean;
    known_by?: unknown[];
    rumors_created?: unknown[];
    beliefs_created?: unknown[];
    consequences_created?: unknown[];
    contradictions_created?: unknown[];
    canon_progression_credit?: {
      stat: "authority" | "ruin" | "creation";
      satisfies_criterion?: string;
      weight?: number;
    }[];
    path_credits?: {
      domain: string;
      weight: number;
    }[];
    /**
     * R-147-P: companion_ids that witnessed this event. Multi-witness mechanics — Bell Court testimony, Drowned Church doctrinal weighting.
     */
    party_member_witnesses?: string[];
    /**
     * R-95-B: map of event-field-path → agent_name that produced it. Debug aid + replay determinism.
     */
    agent_provenance?: {
      [k: string]: string;
    };
    /**
     * R-146-P: combat state inside event. No separate combat entity in v0.5 (deferred bundle).
     */
    combat_state?: {
      /**
       * R-146-P: party-aware initiative order
       */
      initiative_order?: {
        actor_id?: string;
        actor_kind?: "player" | "companion" | "npc" | "creature" | "environment";
        initiative_roll?: number;
      }[];
      round_number?: number;
      current_actor_index?: number;
    } | null;
    /**
     * R-114-D: per-scene catalog of clickable diegetic UI elements with their state. Scoped to events because event has scene context.
     */
    diegetic_elements?: {
      element_id?: string;
      element_kind?:
        | "fountain"
        | "bell"
        | "ledger"
        | "tithing_cup"
        | "vials_shelf"
        | "bell_forge"
        | "marrow_wax_candle"
        | "salt_pan"
        | "litany_card";
      state?: {};
      is_clickable?: boolean;
    }[];
    /**
     * R-118-D: optional ticker-ready summary populated by Narrator. Null when event is not surfaceable.
     */
    public_summary_for_ticker?: string | null;
    /**
     * R-122-E: groups events by scene for easier filtering. Replaces implicit grouping.
     */
    scene_id?: string | null;
  };
  faction?: {
    faction_id: string;
    name: string;
    type?: string;
    region_id?: string;
    core_goal: string;
    fear?: string;
    resources: unknown[];
    territory?: unknown[];
    leadership?: unknown[];
    internal_unity?: number;
    public_legitimacy?: number;
    player_awareness?: number;
    stance_to_player: string;
    fear_of_player?: number;
    trust_in_player?: number;
    dependency_on_player?: number;
    containment_priority?: number;
    active_plans?: unknown[];
    beliefs?: unknown[];
    /**
     * R-145-P: faction-mediated terms per-companion. Keyed by companion_id.
     */
    faction_obligation_state_per_companion?: {
      [k: string]: {
        obligation_kind?: "loan" | "contract" | "gift_debt" | "tithe" | "vigil";
        obligation_terms?: string;
        days_remaining?: number | null;
        violation_state?: "honored" | "drifting" | "violated";
      };
    };
    /**
     * R-123-E: faction plans with scheduled execution day. Per Notice Ladder Tracker timing R-79.
     */
    scheduled_actions?: {
      scheduled_action_id?: string;
      action_kind?: string;
      scheduled_for_day?: number;
      scheduled_for_scene_index?: number | null;
      preconditions?: unknown[];
      cancellation_conditions?: unknown[];
    }[];
  };
  npc?: {
    npc_id: string;
    name: string;
    role: string;
    race_id?: string;
    faction_links?: unknown[];
    desire: string;
    fear: string;
    secret?: string;
    resources?: unknown[];
    relationship_to_player?: string;
    current_plan: string;
    next_action?: string;
    betrayal_threshold?: number;
    loyalty_threshold?: number;
    corruption_exposure?: number;
    memory?: {};
    stats_optional?: DerivedStatsBlock;
    hp_optional?: HpBlock;
    /**
     * R-98-B: per-NPC tracker fields when operating as a Notice-Ladder tracker. Per R-82 Notice Ladder.
     */
    tracker_state?: {
      target_player_id?: string;
      assigned_by_faction_id?: string;
      assignment_event_id?: string;
      last_observation_event_id?: string | null;
      next_scheduled_action_day?: number | null;
      tracker_kind?: "observer" | "agent_provocateur" | "binder" | "executioner";
    } | null;
    /**
     * R-139-P: NPC can be recruited via bond-path (organic-trust-build over multiple scenes).
     */
    recruitable_via_bond?: boolean;
    /**
     * R-140-P: NPC becomes recruitable on this canon-event-kind firing. event_kind reference or null.
     */
    recruitable_via_canon_event?: string | null;
    /**
     * R-108-C (deferred): behavior tree state for NPCs. Awaiting v0.5 NPC behavior tree design pass.
     */
    behavior_tree_state?: {
      current_node?: string;
      goal_stack?: string[];
      blocked_by?: string | null;
      tree_version?: string;
    } | null;
    /**
     * R-110-C (deferred): persistent grudges with weight + source_event_id. NPC memory beyond current_plan.
     */
    grudge_ledger?: {
      target_actor_id?: string;
      weight?: number;
      source_event_id?: string;
      established_day?: number;
      decay_rate_per_day?: number;
    }[];
    /**
     * R-121-E: NPC's witness history. NPC Evaluator uses this for response generation.
     */
    witness_history?: {
      event_id?: string;
      witnessed_on_day?: number;
      perception_quality?: "direct" | "overheard" | "inferred" | "told_about";
    }[];
  };
  rumor?: {
    rumor_id: string;
    source_event_id: string;
    current_claim: string;
    truth_accuracy: number;
    distortion_type?: string;
    emotional_tone?: string;
    spread_level?: number;
    regions_reached?: unknown[];
    factions_amplifying?: unknown[];
    factions_suppressing?: unknown[];
    versions?: unknown[];
    player_reputation_effect?: {};
    status?: string;
  };
  belief?: {
    belief_id: string;
    holder_type: string;
    holder_id: string;
    claim: string;
    truth_status: "true" | "false" | "partial" | "unknown" | "contested";
    confidence: number;
    source_ids?: unknown[];
    emotional_charge?: string;
    behavior_effects?: unknown[];
  };
  consequence?: {
    consequence_id: string;
    source_event_id: string;
    trigger_type: "time" | "condition" | "threshold" | "random" | "discovery";
    trigger_value?: string;
    effect_type: string;
    affected_entities?: unknown[];
    affected_systems?: unknown[];
    severity?: number;
    visibility_to_player?: string;
    preventable?: boolean;
    status: "pending" | "triggered" | "resolved" | "failed" | "cancelled";
    resolution_options?: unknown[];
  };
  state_diff?: {
    state_diff_id: string;
    source_event: string;
    approved: boolean;
    approved_by?: "state_manager";
    validator_chain_pass?: {
      stage_1_input?: boolean;
      stage_2_rules?: boolean;
      stage_3_canon_consistency?: boolean;
      stage_4_canon_progression?: boolean;
      stage_5_contradiction_check?: boolean;
      stage_6_content_boundary?: boolean;
    };
    changes: {
      path: string;
      operation: "set" | "increment" | "append" | "remove" | "replace";
      value: unknown;
    }[];
    created_records?: {};
    /**
     * R-92-B: RNG seed that produced this state_diff. Required for tests/replay_determinism.py.
     */
    replay_seed?: string;
    /**
     * R-94-B: per-stage validator result with reason on failure. Expansion of v0.4 boolean validator_chain_pass.
     */
    validator_chain_pass_detailed?: ValidatorStageResult[];
    /**
     * R-96-B: event_ids this diff depends on having committed first. Required for replay ordering.
     */
    dependency_event_ids?: string[];
  };
  contradiction_ledger_entry?: {
    contradiction_id: string;
    kind:
      | "race_extinction"
      | "deity_death"
      | "deity_birth"
      | "race_emergence"
      | "region_transformation"
      | "rumor_vs_canon"
      | "memory_vs_record"
      | "unmade_event"
      | "named_unnamed"
      | "substrate_exposed"
      | "substrate_dispersed"
      | "other"
      | "companion_memory_disagreement";
    source_event_id: string;
    previous_state_summary?: string;
    new_state_summary?: string;
    resolved: boolean;
    resolution_event_id?: string | null;
    /**
     * R-126-E: contradiction surfacing trigger. R-81 closure.
     */
    surfacing_state?: "dormant" | "surfacing_to_player" | "resolved";
    /**
     * R-126-E: day at which contradiction should surface to player. Null = never auto-surface.
     */
    surface_after_day?: number | null;
  };
  class?: {
    class_id:
      | "barbarian"
      | "bard"
      | "cleric"
      | "druid"
      | "fighter"
      | "monk"
      | "paladin"
      | "ranger"
      | "rogue"
      | "sorcerer"
      | "warlock"
      | "wizard";
    default_calling_name: string;
    hit_die: 6 | 8 | 10 | 12;
    primary_abilities: ("str" | "dex" | "con" | "int" | "wis" | "cha")[];
    /**
     * @minItems 2
     * @maxItems 2
     */
    save_proficiencies: ["str" | "dex" | "con" | "int" | "wis" | "cha", "str" | "dex" | "con" | "int" | "wis" | "cha"];
    skill_choices?: {
      choose?: number;
      from?: string[];
    };
    multiclass_prereq?: {
      ability_minimums?: {
        [k: string]: number;
      };
      regional_restrictions?: string[];
    };
    custom_stat_hooks?: {
      hook_id: string;
      description: string;
      triggers_on?: string;
      modifier_source?: "body" | "grace" | "sense" | "mind" | "will" | "presence" | "authority" | "ruin" | "creation";
    }[];
    spellcasting_kind?: "none" | "full" | "half" | "third" | "pact";
  };
  race?: {
    race_id: string;
    name: string;
    ability_bonuses: {
      [k: string]: number;
    };
    size: "tiny" | "small" | "medium" | "large";
    speed_feet: number;
    darkvision_feet?: number;
    languages_known?: string[];
    languages_choices?: {
      choose?: number;
      from?: string[];
    };
    traits?: {
      trait_id: string;
      description: string;
      custom_stat_hooks?: string[];
    }[];
    subraces?: string[];
    world_mutation_state?: "baseline" | "emergent" | "drift_subrace" | "endangered" | "extinct";
    custom_stat_tilt?: {
      body?: number;
      grace?: number;
      sense?: number;
      mind?: number;
      will?: number;
      presence?: number;
      authority?: number;
      ruin?: number;
      creation?: number;
    };
  };
  subrace?: {
    subrace_id: string;
    parent_race_id: string;
    name: string;
    ability_bonuses?: {
      [k: string]: number;
    };
    extra_traits?: {}[];
    world_mutation_state?: "baseline" | "emergent" | "drift_subrace" | "endangered" | "extinct";
  };
  deity?: {
    deity_id: string;
    name: string;
    alternative_names?: string[];
    alignment: AlignmentDescriptor;
    domains: ("knowledge" | "life" | "light" | "nature" | "tempest" | "trickery" | "war" | "death")[];
    symbol?: string;
    symbol_motif?: string;
    notice_threshold_d100?: number;
    origin?: "baseline" | "regional" | "heretical_reading" | "emergent" | "fragmentary" | "dead" | "unknown";
    regional_origin_id?: string | null;
    status?: "worshipped" | "dormant" | "sleeping" | "dead" | "newborn" | "contested";
    death_event_id?: string | null;
    succession_rule?: {
      on_death?: "void" | "successor_appointed" | "domain_redistributed" | "fragment_into_lesser" | "no_successor";
      successor_candidate_ids?: string[];
    };
    mythological_substrate_refs?: {
      substrate_id: string;
      reading_mode: "inherit" | "distort" | "deny" | "accidental";
    }[];
  };
  pantheon?: {
    pantheon_id: string;
    origin_label: string;
    deity_ids: string[];
    region_ids?: string[];
    status?: "active" | "regional" | "heretical" | "dormant" | "extinct";
    mythological_substrate_refs?: string[];
    regional_configuration?: {
      region_id?: string;
      worshipped_deities?: {
        deity_id: string;
        reading_mode: "orthodox" | "heretical_reading" | "distorted" | "silent_majority" | "suppressed_minority";
        local_epithet?: string;
        doctrine_summary?: string;
      }[];
      heretical_reading_patterns?: (
        | "demoted_mother"
        | "silent_twin"
        | "buried_domain"
        | "forgotten_dawn"
        | "unnamed_among_names"
        | "recanted_heresy"
      )[];
    };
    /**
     * R-125-E: how negative faith values render in UI. R-83 closure.
     */
    faith_meter_negative_value_ui_treatment?: "hidden_in_ui" | "shown_as_apostate" | "shown_as_explicit_negative";
  };
  spell?: {
    spell_id: string;
    name: string;
    level: number;
    school:
      | "abjuration"
      | "conjuration"
      | "divination"
      | "enchantment"
      | "evocation"
      | "illusion"
      | "necromancy"
      | "transmutation"
      | "regional";
    regional_school_id?: string | null;
    regional_origin_id?: string | null;
    regional_pantheon_alignment?: string | null;
    casting_time: string;
    range: string;
    components: {
      v?: boolean;
      s?: boolean;
      m?: boolean;
      m_text?: string;
      m_consumed?: boolean;
      m_cost_gp?: number;
    };
    duration: DurationObject;
    concentration?: boolean;
    ritual_eligible?: boolean;
    save_type?: null | "str" | "dex" | "con" | "int" | "wis" | "cha";
    attack_kind?: null | "melee" | "ranged";
    damage_dice?: string | null;
    damage_type?: string | null;
    classes_allowed: string[];
    domain_aligned?: string[];
    cost_layer?: SpellCostLayer;
    description_template?: string;
    /**
     * Tooling/content tags (slice_eligible, imposed_eligible, etc.). Replaces semantic misuse of domain_aligned for tagging.
     */
    tags?: string[];
    /**
     * Explicit flag: this spell creates a canon event when cast. Helps State Manager event-emission logic vs. inferring from cost_layer.
     */
    creates_canon_event_on_cast?: boolean;
    /**
     * Subschool within parent school. 14 subschools used in v0.4.3 originals.
     */
    subschool?:
      | "forbiddings"
      | "witness_spells"
      | "listening"
      | "marking_spells"
      | "naming_spells"
      | "contradiction_burst"
      | "resonance"
      | "unbecoming"
      | "memory_spells"
      | "echoes"
      | "lattice_shifts"
      | "inversions"
      | "half_summon"
      | "borrowed_things";
    /**
     * One-line distinctive mechanical twist of an original spell. Surfaced in spell-picker UI for discoverability.
     */
    wild_twist?: string;
  };
  condition?: {
    condition_id: string;
    name: string;
    scope: "universal" | "regional";
    source_pack?: string | null;
    abbreviation?: string;
    ui_glyph: string;
    ui_category?: "metaphysical" | "social_legal" | "physical" | "lethal_tracking";
    stackable?: boolean;
    level_based?: boolean;
    max_level?: number;
    duration_types_allowed?: string[];
    effect_rules?: string;
    removal_methods?: string[];
  };
  item?:
    | WeaponItem
    | ArmorItem
    | ShieldItem
    | AmmunitionItem
    | ToolItem
    | TrinketItem
    | ConsumableItem
    | WondrousItem
    | BookItem
    | KeyItem
    | CurrencyTokenItem;
  recipe?: {
    recipe_id: string;
    name: string;
    track?: "forging" | "tinkering" | "alchemy";
    tool_required?: string;
    station_required?: string;
    ingredients?: {
      item_id: string;
      quantity: number;
      consumed?: boolean;
    }[];
    output_item_id?: string;
    output_quantity?: number;
    workday_cost?: number;
    gp_cost?: number;
    difficulty_dc?: number;
    ability_check?: null | "str" | "dex" | "con" | "int" | "wis" | "cha";
    regional_origin_id?: string | null;
    branching_outcomes?:
      | {
          dc_band: string;
          outcome_item_id?: string;
          side_effect_kind?: string;
          [k: string]: unknown;
        }[]
      | {
          [k: string]: string;
        };
    witness_inheritance?:
      | null
      | unknown[]
      | {
          [k: string]: unknown;
        };
    invisible_work?:
      | null
      | unknown[]
      | {
          [k: string]: unknown;
        };
    /**
     * R-120-E: M2 finding R-85. If primary station inaccessible, list of fallbacks with consequences.
     */
    station_alternative_routes?: {
      fallback_station_id?: string;
      dc_modifier?: number;
      yield_modifier?: number;
      narrative_consequence?: string;
    }[];
    materials: {
      material_id: string;
      quantity: number;
      consent_required_at_acquisition?: boolean;
      is_witness_bearing?: boolean;
      consumed_in_minting?: boolean;
      partial_consumption_units?: number;
      [k: string]: unknown;
    }[];
    produces_item_id: string;
    primary_station_id?: string;
    alternative_station_ids?: string[];
    time_in_world_hours?: number;
    tags?: string[];
    craft_track?: string;
    skill_check?: string;
    dc?: number;
  };
  region?: {
    region_id: string;
    name: string;
    status: "active" | "starting" | "transformed" | "lost" | "dream" | "abyssal" | "future";
    framing_notes?: string;
    regional_pack_refs?: RegionalPackRef[];
    active_pantheon_id?: string;
    active_pantheon_config_id?: string;
    currency_pack_id?: string;
    conditions_pack_id?: string;
    magic_traditions_pack_id?: string;
    cult_institution_refs?: string[];
    heretical_reading_pattern_refs?: (
      | "demoted_mother"
      | "silent_twin"
      | "buried_domain"
      | "forgotten_dawn"
      | "unnamed_among_names"
      | "recanted_heresy"
    )[];
    substrate_exposed_refs?: string[];
    /**
     * R-130-F (speculative): weather as world-state. Currently narrated, not modeled.
     */
    weather_state?: {
      current_weather_kind?: string;
      since_day?: number;
      intensity?: number;
    } | null;
    /**
     * R-130-F (speculative): historical weather log.
     */
    weather_history?: {}[];
  };
  regional_pack?: {
    pack_id: string;
    region_id: string;
    kind:
      | "conditions"
      | "currencies"
      | "magic_traditions"
      | "pantheon"
      | "items"
      | "recipes"
      | "factions"
      | "deities"
      | "litanies"
      | "marginalia"
      | "substrate"
      | "loot_tables"
      | "materials"
      | "cult_institutions"
      | "environment";
    version?: string;
    contents_path?: string;
  };
  mythological_substrate_entry?: {
    substrate_id: string;
    name_descriptor?: string;
    kind: "pattern" | "proto_deity" | "era_marker" | "fragment";
    era_band?: {
      from?: string;
      to?: string;
    };
    status: "dormant" | "exposed" | "bound" | "dispersed" | "renamed";
    patterns_invoked?: string[];
    fragments_known?: string[];
    active_deity_readings?: string[];
    exposure_method?: string[];
    world_impact_if_exposed?: string;
    min_exposure_cooldown_days?: number;
    drawn_from?: string;
    what_we_did_not_take?: string;
  };
  loot_table?: {
    loot_table_id: string;
    scope: "carried" | "hidden" | "yielded" | "canon_event_drop";
    trigger_event_kind: string;
    region_id?: string | null;
    location_id?: string | null;
    faction_id?: string | null;
    rolls: {
      kind?: "guaranteed" | "weighted" | "memory";
      item_id?: string | null;
      qty?: number;
      qty_die?: string;
      weights?: unknown[];
      creates_item_id_template?: string;
      weight?: number;
      condition?: string;
    }[];
    refusal_consequences?: {
      claimable_by_factions?: string[];
      decay_pattern?: string;
      rumor_risk?: boolean;
    };
    /**
     * Version flag indicating creates_item_id_template fields parse against the v0.5 grammar: variables marked as ${var_name}, substitutions resolved by State Manager at canon-event.
     */
    template_grammar_version?: "v0.5";
  };
  material?: {
    material_id: string;
    name: string;
    category: "material_metal" | "material_stone" | "material_wood" | "material_fiber" | "material_reagent";
    tinting_class?:
      | "vellum_mundane"
      | "brass_greywake"
      | "tide_bloom_metaphysical"
      | "verdigris_consumable"
      | "drowned_red_cursed"
      | "bone_relic"
      | "cursed_substrate";
    regional_origin_id?: string | null;
    weight_kg_per_unit?: number;
    value_cp_per_unit?: number;
    witness_payload?: null | {
      witness_summary?: string;
      binding_dc?: number;
      carries_soul_kind?: null | "witness" | "spirit" | "fragment" | "echo";
      carries_memory_tags?: string[];
      /**
       * SC-07: ordered history of past holders/uses, for items that carry deep memory.
       */
      provenance_chain?: {
        holder_id?: string;
        held_from_day?: number;
        held_until_day?: number | null;
        transfer_event_id?: string | null;
        transfer_kind?: "gifted" | "stolen" | "won" | "inherited" | "harvested" | "salvaged";
      }[];
    };
    /**
     * Material tier; T1<=50cp, T2=51-500, T3=501-5000, T4>5000. Was previously inferred from value_cp_per_unit bands.
     */
    tier?: "T1" | "T2" | "T3" | "T4";
    /**
     * Material is approved for M8 Greywake slice ship. Replaces memory_tag interim flag.
     */
    slice_eligible?: boolean;
    /**
     * Material is a craft-intermediate, not a primary harvestable resource. E.g., vial_of_practiced_name_water.
     */
    is_intermediate?: boolean;
    /**
     * Where this material is sourced: biome / region kind / institution control. E.g., ['salt_marsh', 'coastal', 'drowned_church_grounds'].
     */
    sourcing_geography?: string[];
    /**
     * Decay rules — material crumbles or transforms outside given context. E.g., salt-rime outside region_greywake.
     */
    decay_states?: {
      decay_kind?: "region_locked" | "time_locked" | "ritual_locked" | "concentration_locked";
      decay_trigger?: string;
      decay_outcome?: string;
    }[];
    /**
     * Explicit list of craft tracks that may use this material.
     */
    craft_tracks_eligible?: ("forging" | "alchemy" | "tinkering" | "scribing" | "ritual")[];
    /**
     * How this material becomes obtainable. Some (e.g., mat_listening_child_pebble) cannot be purchased.
     */
    acquisition_method?: "purchased" | "gifted_only" | "harvested" | "quest_reward" | "canon_event_only" | "crafted";
    notes?: string;
  };
  regional_currency_state?: {
    currency_id: string;
    region_id: string;
    base_value_gp: number;
    volatility_modifier: number;
    crisis_intensity_modifier: 1 | 0.85 | 0.6 | 0.4 | 1.2 | 0.05;
    crisis_label?: "calm" | "rumored_crisis" | "declared_crisis" | "acute_crisis" | "resolved" | "collapsed";
    last_recompute_event_id?: string;
  };
  cult_institution?: {
    cult_institution_id: string;
    faction_id: string;
    region_id: string;
    primary_deity_ids?: string[];
    clerical_archetype?: string;
    doctrines?: {
      doctrine_id: string;
      text: string;
      faith_meter_aligned?: {
        deity_id?: string;
        alignment_kind?: "tenets_aligned" | "tenets_violating";
      };
    }[];
    taboos?: {
      taboo_id: string;
      text: string;
      violation_consequence: {
        notice_delta?: number;
        path_credit?: {};
        faith_delta?: {};
        social_response?: string;
      };
    }[];
    rite_kinds?: ("daily" | "weekly" | "seasonal" | "lunar" | "tidal" | "canon_event")[];
    heretical_figures?: string[];
  };
  creature_material?: {
    creature_material_id: string;
    name: string;
    source_creature_kinds: string[];
    harvest_kind: "hide" | "blood" | "bone" | "scale" | "tooth" | "organ" | "feather" | "venom" | "ichor" | "shell";
    yield_per_creature?: {
      min?: number;
      max?: number;
      unit?: string;
    };
    /**
     * Dice DC for clean harvest
     */
    harvest_dc?: number;
    harvest_skill?: "body" | "grace" | "sense" | "mind" | "will";
    preservation_required?: boolean;
    preservation_method?: string;
    value_cp_per_unit?: number;
    /**
     * Some creature materials carry witness (e.g., a Drowned Church saint's bone)
     */
    witness_payload?: {} | null;
    tier?: "T1" | "T2" | "T3" | "T4";
    craft_tracks_eligible?: string[];
    decay_states?: unknown[];
    regional_pack_id?: string | null;
  };
  material_substitution?: {
    substitution_id: string;
    recipe_id: string;
    primary_material_id: string;
    alternative_material_id: string;
    /**
     * DC adjustment when alternative is used (typically positive)
     */
    dc_modifier?: number;
    /**
     * Multiplier on yield when alternative used
     */
    yield_modifier?: number;
    /**
     * Why this substitution exists in-world
     */
    narrative_tag?: string;
  };
  companion?: {
    companion_id: string;
    name: string;
    underlying_npc_id: string;
    recruitment_path: "quest" | "bond" | "faction_mediated" | "canon_event_emergent";
    recruited_on_day: number;
    recruited_event_id?: string;
    /**
     * R-135-P: faction-mediated terms (loan/contract/gift)
     */
    terms?: {
      kind?: null | "gift" | "loan" | "contract";
      duration_days?: number | null;
      scheduled_recall_day?: number | null;
      obligations?: string[];
      violation_consequence?: string;
    } | null;
    /**
     * R-136-P: 8-driver layer governing autonomous behavior between scenes
     */
    autonomous_drivers?: {
      loyalty?: number;
      personality_tags?: string[];
      /**
       * References to quirk schema entries
       */
      quirks?: string[];
      faith_meters?: {};
      path_alignment?: {};
      faction_loyalty?: {};
      witness_state?: {};
      desire_fear?: {
        desires?: unknown[];
        fears?: unknown[];
      };
    };
    /**
     * R-141-P: lifecycle state
     */
    party_tier_state?: "with_player" | "separately_acting" | "dismissed_or_resting";
    /**
     * R-142-P: events this companion has witnessed (for witness-bearing mechanics)
     */
    witnessed_event_ids?: string[];
    /**
     * R-143-P: companions accumulate their own canon-progression credit; can experience X.12-X.16 endings
     */
    canon_progression_credit?: {
      authority?: number;
      ruin?: number;
      creation?: number;
      corruption?: number;
    };
    /**
     * Full stat block; same shape as player.stats_block
     */
    stats_block?: {};
    inventory?: unknown[];
    hp_block?: HpBlock;
    meters_block?: MetersBlock;
    conditions_active?: unknown[];
    is_dead?: boolean;
    death_state?: {} | null;
  };
  orchestrator_session?: {
    session_id: string;
    campaign_id: string;
    player_user_id?: string;
    session_start_at?: string;
    session_end_at?: string | null;
    /**
     * Deterministic seed for this session's RNG stream
     */
    rng_seed: string;
    /**
     * Number of RNG draws consumed so far
     */
    rng_stream_position?: number;
    agent_call_log?: {
      agent_name?: string;
      called_at?: string;
      envelope_id?: string;
      tokens_in?: number;
      tokens_out?: number;
      model_id?: string;
      latency_ms?: number;
    }[];
    active?: boolean;
    last_state_diff_id?: string | null;
  };
  agent_envelope?: {
    envelope_id: string;
    session_id: string;
    agent_name:
      | "input_interpreter"
      | "rules_agent"
      | "npc_evaluator"
      | "faction_evaluator"
      | "domain_evaluator"
      | "world_director"
      | "dice_resolution"
      | "state_manager"
      | "narrator"
      | "content_boundary_validator";
    stage_index: number;
    input_payload?: {};
    output_payload?: {};
    validator_pass?: boolean;
    called_at?: string;
    completed_at?: string | null;
    error?: string | null;
    model_id?: string;
    tokens_in?: number;
    tokens_out?: number;
  };
  quirk?: {
    quirk_id: string;
    name: string;
    description_template: string;
    behavioral_modifier?: {
      scene_kind_attraction?: {};
      scene_kind_aversion?: {};
      interjection_trigger?: string;
      suggestion_bias?: {};
    };
    intensity?: number;
  };
  recruitment_quest?: {
    quest_id: string;
    target_companion_id: string;
    stages?: {
      stage_id?: string;
      name?: string;
      completion_criteria?: string;
      rewards?: unknown[];
      branching_outcomes?: unknown[];
    }[];
    /**
     * What is offered to the player at quest completion (often the companion joining)
     */
    completion_offer?: {};
    abandonment_consequences?: {};
  };
  location?: {
    location_id: string;
    region_id: string;
    name: string;
    discovered_by_player_event_id?: string | null;
    fog_of_knowledge_state?: "unknown" | "glimpsed" | "visited" | "known";
    parent_location_id?: string | null;
  };
  travel_route?: {
    route_id: string;
    from_location_id: string;
    to_location_id: string;
    traversal_cost_hours?: number;
    traversal_risk?: "safe" | "watched" | "dangerous" | "deadly";
    knowledge_required?: string[];
  };
  conflict_envelope?: {
    envelope_id: string;
    kind: "physical" | "social" | "magical" | "ritual" | "economic" | "factional" | "mythological" | "metaphysical";
    parties: string[];
    stakes?: string;
    resolution_path?: string;
    /**
     * Variant payload per kind; shape determined by kind value (deferred design pass)
     */
    kind_specific_fields?: {};
  };
  portrait_layer_definition?: {
    layer_id: string;
    layer_kind:
      | "race_silhouette"
      | "class_glyph"
      | "alignment_tint"
      | "condition_overlay"
      | "body_mod_overlay"
      | "curated_event_overlay";
    svg_path: string;
    /**
     * What state condition (e.g., faith>=5_to_unnamed, condition_id=bonded_to_marrow_saint) triggers this overlay
     */
    triggered_by?: {};
    anchor_point?: string;
  };
  imposed_spell?: {
    spell_id: string;
    name: string;
    level: number;
    school:
      | "abjuration"
      | "conjuration"
      | "divination"
      | "enchantment"
      | "evocation"
      | "illusion"
      | "necromancy"
      | "transmutation"
      | "regional";
    regional_school_id: string;
    regional_origin_id: string;
    regional_pantheon_alignment?: string | null;
    casting_time: string;
    range: string;
    components: {
      v?: boolean;
      s?: boolean;
      m?: boolean;
      m_text?: string;
      m_consumed?: boolean;
      m_cost_gp?: number;
    };
    duration: DurationObject;
    concentration?: boolean;
    ritual_eligible?: boolean;
    save_type?: null | "str" | "dex" | "con" | "int" | "wis" | "cha";
    attack_kind?: null | "melee" | "ranged";
    damage_dice?: string | null;
    damage_type?: string | null;
    classes_allowed: string[];
    domain_aligned?: string[];
    cost_layer?: SpellCostLayer;
    description_template?: string;
    /**
     * Tooling/content tags (slice_eligible, imposed_eligible, etc.). Replaces semantic misuse of domain_aligned for tagging.
     */
    tags?: string[];
    /**
     * Explicit flag: this spell creates a canon event when cast. Helps State Manager event-emission logic vs. inferring from cost_layer.
     */
    creates_canon_event_on_cast?: boolean;
    /**
     * Subschool within parent school. 14 subschools used in v0.4.3 originals.
     */
    subschool?:
      | "forbiddings"
      | "witness_spells"
      | "listening"
      | "marking_spells"
      | "naming_spells"
      | "contradiction_burst"
      | "resonance"
      | "unbecoming"
      | "memory_spells"
      | "echoes"
      | "lattice_shifts"
      | "inversions"
      | "half_summon"
      | "borrowed_things";
    /**
     * One-line distinctive mechanical twist of an original spell. Surfaced in spell-picker UI for discoverability.
     */
    wild_twist?: string;
  };
  litany?: {
    litany_id: string;
    title: string;
    text_body: string;
    mechanical_effect?:
      | string
      | {
          [k: string]: unknown;
        };
    voice_register?: string;
    rite_kind?: string;
    faction_origin?: string;
    first_heard_default_npc?: string;
    origin_institution?: string;
    canonical_use?: string;
    tags?: string[];
    tone_tags?: string[];
    regional_origin_id?: string | null;
    schema_version?: "v1" | "v2";
  };
  marginalia?: {
    marginalia_id: string;
    text: string;
    trigger_kind?:
      | "canon_progression_event"
      | "state_threshold"
      | "item_acquired"
      | "item_event"
      | "location_entered"
      | "npc_interaction"
      | "npc_speech_anomaly"
      | "scene_end"
      | "rite"
      | "manual"
      | "faction_action"
      | "social_conflict"
      | "weather_omen"
      | "time_progression";
    trigger_event_kind?: string;
    trigger_condition?: string;
    display_context?:
      | "player_journal_at_end_of_scene"
      | "inline_in_narration"
      | "inline_during_scene"
      | "inline_at_scene_open"
      | "inline_at_scene_close"
      | "tome_unlock"
      | "world_pulse_ticker";
    tone_tags?: string[];
    regional_origin_id?: string | null;
    schema_version?: "v1" | "v2";
  };
  opex_state?: {
    /**
     * YYYY-MM-DD; primary key. Lazy reset on first read of a new date.
     */
    utc_date: string;
    /**
     * Running total spent today across all agents and models, in USD.
     */
    daily_spend_usd: number;
    /**
     * Configured ceiling for this date. When daily_spend_usd >= daily_cap_usd, premium tier is unavailable.
     */
    daily_cap_usd: number;
    /**
     * Per-session token budget tracking (in-memory mirror of DB rows for fast cap checks).
     */
    session_budgets?: {
      session_id: string;
      tokens_consumed: number;
      tokens_budget: number;
      created_at_iso?: string;
    }[];
    last_updated_iso?: string;
  };
  opex_event?: {
    event_id: string;
    timestamp_iso: string;
    agent:
      | "narrator"
      | "state_manager"
      | "validator_input"
      | "validator_rules"
      | "validator_consistency"
      | "validator_progression"
      | "validator_contradiction"
      | "validator_boundary"
      | "form_of_ending"
      | "postcard"
      | "voice_evaluator"
      | "other";
    model_id: string;
    tier: "premium" | "mid" | "cheap";
    tokens_in: number;
    tokens_out: number;
    est_cost_usd: number;
    fallback_reason?:
      | null
      | "daily_cap_hit"
      | "session_budget_exhausted"
      | "primary_failure"
      | "manual_override"
      | "tier_policy_default";
    success: boolean;
    error_kind?: string | null;
    session_id?: string | null;
    latency_ms?: number;
  };
  model_tier_policy?: {
    policy_id: string;
    version?: string;
    last_updated_iso?: string;
    daily_cap_usd?: number;
    per_session_token_budget?: number;
    /**
     * Maps agent_id to default tier under normal conditions.
     */
    agent_tiers: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z_]+$".
       */
      [k: string]: "premium" | "mid" | "cheap";
    };
    /**
     * Maps tier to ordered list of model_ids. Tried in order; first success wins.
     */
    fallback_chains: {
      /**
       * @minItems 1
       */
      premium: [string, ...string[]];
      /**
       * @minItems 1
       */
      mid: [string, ...string[]];
      /**
       * @minItems 1
       */
      cheap: [string, ...string[]];
    };
    max_fallback_attempts?: number;
    /**
     * Buffer on daily cap to absorb concurrent-Lambda race condition. e.g., 0.1 = stop at 90% of cap.
     */
    cap_buffer_pct?: number;
  };
}
export interface WorldTime {
  day: number;
  scene_index: number;
  tide_phase?: "low" | "rising" | "high" | "falling" | "still";
  calendar_label?: string;
}
export interface RegionalPackRef {
  region_id: string;
  kind:
    | "conditions"
    | "currencies"
    | "magic_traditions"
    | "pantheon"
    | "items"
    | "recipes"
    | "factions"
    | "deities"
    | "litanies"
    | "marginalia"
    | "substrate"
    | "loot_tables"
    | "materials"
    | "cult_institutions"
    | "environment";
  pack_version?: string;
}
export interface CustomStatsBlock {
  body: number;
  grace: number;
  sense: number;
  mind: number;
  will: number;
  presence: number;
  authority: number;
  ruin: number;
  creation: number;
}
export interface DerivedStatsBlock {
  str: AbilityScore;
  dex: AbilityScore;
  con: AbilityScore;
  int: AbilityScore;
  wis: AbilityScore;
  cha: AbilityScore;
}
export interface MetersBlock {
  fatigue: BoundedInt_0_10;
  clarity: BoundedInt_0_10;
  debt: BoundedInt_0_10;
  notice: BoundedInt_0_10;
  corruption: BoundedInt_0_10;
}
export interface HpBlock {
  current: number;
  max: number;
  temp?: number;
  death_save_successes?: number;
  death_save_failures?: number;
}
export interface HitDiceEntry {
  class_id: string;
  die_size: 6 | 8 | 10 | 12;
  total: number;
  remaining: number;
}
export interface ConditionActiveInstance {
  condition_id: string;
  duration: DurationObject;
  source?: string;
  stacks?: number;
}
export interface SpellSlotTable {
  /**
   * This interface was referenced by `SpellSlotTable`'s JSON-Schema definition
   * via the `patternProperty` "^slot_[1-9]$".
   */
  [k: string]: number;
}
export interface KnownSpellEntry {
  spell_id: string;
  prepared?: boolean;
  source?: "class" | "race" | "feat" | "item" | "pact" | "canon_event";
  ritual_eligible?: boolean;
}
export interface InventoryEntry {
  item_id: string;
  quantity: number;
  identified?: boolean;
  attuned_slot_index?: number | null;
  equipped_slot?:
    | null
    | "main_hand"
    | "off_hand"
    | "two_handed"
    | "armor"
    | "shield"
    | "helm"
    | "cloak"
    | "boots"
    | "gloves"
    | "ring_1"
    | "ring_2"
    | "amulet"
    | "belt";
  bound_to_you?: boolean;
  soul_instance?: {
    soul_id?: string;
    depth?: number;
    kind?: "witness" | "spirit" | "fragment" | "echo";
    bound_by_event_id?: string;
    speaks?: boolean;
    speaks_threshold?: {
      meter?: "fatigue" | "clarity" | "debt" | "notice" | "corruption";
      value?: number;
    };
    claims?: string[];
    demands?: string[];
    dormant_unless?: string[];
  };
  memory_instance?: {
    entries?: {
      memory_id: string;
      timestamp_world?: WorldTime;
      witness_summary: string;
      actor_ids?: string[];
      tags?: string[];
    }[];
    readable_via?: (
      | "legend_lore_spell"
      | "speak_with_dead_on_origin"
      | "imposed_unrecord_inverted"
      | "alchemy_purgative_inversion"
      | "sense_check"
    )[];
  };
}
export interface AttunementSlot {
  slot_index: number;
  status: "empty" | "attuned" | "sworn" | "cursed" | "scarred";
  item_id?: string | null;
  attuned_at?: string;
  ceremony_kind?: "short_rest" | "salt_immersion" | "sworn_oath" | "blood_consecration" | "involuntary_curse";
  break_conditions?: ("dis-engagement" | "trauma" | "competing_claim" | "remove_curse" | "canon_event")[];
  /**
   * v0.4 Bundle A: when sworn slot is broken or fulfilled, may scar; cannot accept new attunement until this in-world day.
   */
  scarred_until_day?: number | null;
}
export interface CurrencyAmount {
  cp?: number;
  sp?: number;
  ep?: number;
  gp?: number;
  pp?: number;
  regional?: {
    [k: string]: number;
  };
}
export interface FaithMeterEntry {
  deity_id: string;
  value: BoundedIntNeg10Pos10;
  apostate_history?: string[];
}
export interface PathLedgerEntry {
  entry_id: string;
  domain:
    | "law"
    | "faith"
    | "mercy"
    | "cruelty"
    | "promise"
    | "oath"
    | "debt"
    | "ruin"
    | "creation"
    | "loyalty"
    | "betrayal"
    | "curiosity"
    | "silence"
    | "hubris"
    | "tithe"
    | "tapu_violation";
  weight: number;
  source_event_id: string;
  timestamp: WorldTime;
  narrative_phrase?: string;
}
export interface CanonProgressionEntry {
  stat: "authority" | "ruin" | "creation";
  current_value: BoundedInt_0_10;
  progress_toward_next: number;
  criteria_required?: number;
  asi_sacrifices_spent: number;
  /**
   * v0.4.1 (R-86): in-world day until which a spent end-condition threshold cannot retrigger. Set when player refuses apotheosis (X.12), self-unmaking (X.13), or withdrawal (X.14). null means threshold is not in spent state. State Manager owns set; clears automatically when current_time.day exceeds this value.
   */
  threshold_spent_until_day?: number | null;
  criteria_events?: string[];
  side_effects_applied?: {
    stat_or_meter: string;
    delta: number;
  }[];
}
export interface BodyModificationsBlock {
  grafts?: {
    graft_id?: string;
    /**
     * R-99-C: constrained vocabulary; Greywake-native frame locked
     */
    kind?:
      | "brass_spinal_brace"
      | "bone_lattice_lung"
      | "salt_iron_jaw_brace"
      | "marrow_wax_eye"
      | "drowned_amber_hand"
      | "bell_iron_chest_plate";
    grafted_on_day?: number;
    grafter_npc_id?: string;
    is_reversible?: boolean;
  }[];
  symbionts?: {
    symbiont_id?: string;
    /**
     * R-100-C
     */
    host_relationship?: "parasitic" | "commensal" | "mutualist" | "contested";
  }[];
  fusions?: {
    fusion_id?: string;
    /**
     * R-101-C: canon-event that could reverse, if reversible
     */
    reversibility_event_id?: string | null;
  }[];
  /**
   * R-102-C: bottled mutagenic relics currently active
   */
  adaptagen_active?: {}[];
}
/**
 * Deferred bundle (mad-sci track). Schema slot pre-wired per v0.4 Bundle A; awaiting design pass.
 */
export interface BodyModificationsBlock1 {
  grafts?: {
    graft_id?: string;
    /**
     * R-99-C: constrained vocabulary; Greywake-native frame locked
     */
    kind?:
      | "brass_spinal_brace"
      | "bone_lattice_lung"
      | "salt_iron_jaw_brace"
      | "marrow_wax_eye"
      | "drowned_amber_hand"
      | "bell_iron_chest_plate";
    grafted_on_day?: number;
    grafter_npc_id?: string;
    is_reversible?: boolean;
  }[];
  symbionts?: {
    symbiont_id?: string;
    /**
     * R-100-C
     */
    host_relationship?: "parasitic" | "commensal" | "mutualist" | "contested";
  }[];
  fusions?: {
    fusion_id?: string;
    /**
     * R-101-C: canon-event that could reverse, if reversible
     */
    reversibility_event_id?: string | null;
  }[];
  /**
   * R-102-C: bottled mutagenic relics currently active
   */
  adaptagen_active?: {}[];
}
export interface ValidatorStageResult {
  stage_id:
    | "stage_1_input"
    | "stage_2_rules"
    | "stage_3_canon_consistency"
    | "stage_4_canon_progression"
    | "stage_5_contradiction_check"
    | "stage_6_content_boundary";
  pass: boolean;
  /**
   * Failure reason; null on pass
   */
  reason?: string | null;
  validator_id: string;
  completed_at?: string;
}
/**
 * R-51 universal canon-cost on leveled spellcasting. Cantrips remain free.
 */
export interface SpellCostLayer {
  fatigue?: number;
  notice?: number;
  corruption?: number;
  authority?: number;
  ruin?: number;
  creation?: number;
  scaling_rule?: string;
}
export interface WeaponItem {
  type?: "weapon";
  subtype?: null | "simple_melee" | "simple_ranged" | "martial_melee" | "martial_ranged";
  damage_dice: string;
  damage_type:
    | "bludgeoning"
    | "piercing"
    | "slashing"
    | "fire"
    | "cold"
    | "lightning"
    | "thunder"
    | "force"
    | "radiant"
    | "necrotic"
    | "psychic"
    | "acid"
    | "poison";
  weapon_properties?: string[];
}
export interface ArmorItem {
  type?: "armor";
  subtype?: "light" | "medium" | "heavy";
  armor_ac_base: number;
  armor_dex_cap?: number;
  armor_stealth_disadvantage?: boolean;
  armor_strength_min?: number;
}
export interface ShieldItem {
  type?: "shield";
  armor_ac_base: number;
}
export interface AmmunitionItem {
  type?: "ammunition";
  subtype: "arrows" | "bolts" | "sling_stones" | "bullets" | "needles" | "darts";
}
export interface ToolItem {
  type?: "tool";
}
export interface TrinketItem {
  type?: "trinket";
}
export interface ConsumableItem {
  type?: "consumable";
}
export interface WondrousItem {
  type?: "wondrous";
}
export interface BookItem {
  type?: "book";
}
export interface KeyItem {
  type?: "key";
}
export interface CurrencyTokenItem {
  type?: "currency_token";
}


// ============================================================================
// Per-entity type aliases — ergonomic exports.
// Suffix "Schema" avoids collisions with runtime types in index.ts.
// ============================================================================

export type CampaignSchema = NonNullable<FirstPerceptionSchemaPack["campaign"]>;
export type PlayerSchema = NonNullable<FirstPerceptionSchemaPack["player"]>;
export type EventSchema = NonNullable<FirstPerceptionSchemaPack["event"]>;
export type FactionSchema = NonNullable<FirstPerceptionSchemaPack["faction"]>;
export type NpcSchema = NonNullable<FirstPerceptionSchemaPack["npc"]>;
export type RumorSchema = NonNullable<FirstPerceptionSchemaPack["rumor"]>;
export type BeliefSchema = NonNullable<FirstPerceptionSchemaPack["belief"]>;
export type ConsequenceSchema = NonNullable<FirstPerceptionSchemaPack["consequence"]>;
export type StateDiffSchema = NonNullable<FirstPerceptionSchemaPack["state_diff"]>;
export type ContradictionLedgerEntrySchema = NonNullable<FirstPerceptionSchemaPack["contradiction_ledger_entry"]>;
export type ClassSchema = NonNullable<FirstPerceptionSchemaPack["class"]>;
export type RaceSchema = NonNullable<FirstPerceptionSchemaPack["race"]>;
export type SubraceSchema = NonNullable<FirstPerceptionSchemaPack["subrace"]>;
export type DeitySchema = NonNullable<FirstPerceptionSchemaPack["deity"]>;
export type PantheonSchema = NonNullable<FirstPerceptionSchemaPack["pantheon"]>;
export type SpellSchema = NonNullable<FirstPerceptionSchemaPack["spell"]>;
export type ConditionSchema = NonNullable<FirstPerceptionSchemaPack["condition"]>;
export type ItemSchema = NonNullable<FirstPerceptionSchemaPack["item"]>;
export type RecipeSchema = NonNullable<FirstPerceptionSchemaPack["recipe"]>;
export type RegionSchema = NonNullable<FirstPerceptionSchemaPack["region"]>;
export type RegionalPackSchema = NonNullable<FirstPerceptionSchemaPack["regional_pack"]>;
export type MythologicalSubstrateEntrySchema = NonNullable<FirstPerceptionSchemaPack["mythological_substrate_entry"]>;
export type LootTableSchema = NonNullable<FirstPerceptionSchemaPack["loot_table"]>;
export type MaterialSchema = NonNullable<FirstPerceptionSchemaPack["material"]>;
export type RegionalCurrencyStateSchema = NonNullable<FirstPerceptionSchemaPack["regional_currency_state"]>;
export type CultInstitutionSchema = NonNullable<FirstPerceptionSchemaPack["cult_institution"]>;
export type CreatureMaterialSchema = NonNullable<FirstPerceptionSchemaPack["creature_material"]>;
export type MaterialSubstitutionSchema = NonNullable<FirstPerceptionSchemaPack["material_substitution"]>;
export type CompanionSchema = NonNullable<FirstPerceptionSchemaPack["companion"]>;
export type OrchestratorSessionSchema = NonNullable<FirstPerceptionSchemaPack["orchestrator_session"]>;
export type AgentEnvelopeSchema = NonNullable<FirstPerceptionSchemaPack["agent_envelope"]>;
export type QuirkSchema = NonNullable<FirstPerceptionSchemaPack["quirk"]>;
export type RecruitmentQuestSchema = NonNullable<FirstPerceptionSchemaPack["recruitment_quest"]>;
export type LocationSchema = NonNullable<FirstPerceptionSchemaPack["location"]>;
export type TravelRouteSchema = NonNullable<FirstPerceptionSchemaPack["travel_route"]>;
export type ConflictEnvelopeSchema = NonNullable<FirstPerceptionSchemaPack["conflict_envelope"]>;
export type PortraitLayerDefinitionSchema = NonNullable<FirstPerceptionSchemaPack["portrait_layer_definition"]>;
export type ImposedSpellSchema = NonNullable<FirstPerceptionSchemaPack["imposed_spell"]>;
export type LitanySchema = NonNullable<FirstPerceptionSchemaPack["litany"]>;
export type MarginaliaSchema = NonNullable<FirstPerceptionSchemaPack["marginalia"]>;
export type OpexStateSchema = NonNullable<FirstPerceptionSchemaPack["opex_state"]>;
export type OpexEventSchema = NonNullable<FirstPerceptionSchemaPack["opex_event"]>;
export type ModelTierPolicySchema = NonNullable<FirstPerceptionSchemaPack["model_tier_policy"]>;


// ============================================================================
// Generated from schema_pack v0.8.0
// Entity count: 43
// $defs count:  40
// Source: content/schemas/schema_pack_v0.8.json
// ============================================================================
