#!/usr/bin/env node
/**
 * generate-types.mjs — Generate TypeScript types from schema_pack_v0.6.json
 *
 * Reads:   content/schemas/schema_pack_v0.6.json
 * Writes:  packages/types/src/generated.ts
 *
 * Phase 19 / SCHEMA-402: bumps from v0.5 to v0.6. Behavior identical otherwise.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SCHEMA_PATH = resolve(ROOT, "content/schemas/schema_pack_v0.6.json");
const OUT_PATH = resolve(ROOT, "packages/types/src/generated.ts");

const BANNER = [
  "/**",
  " * ============================================================================",
  " * AUTO-GENERATED — DO NOT EDIT",
  " * ============================================================================",
  " * Generated by scripts/generate-types.mjs from content/schemas/schema_pack_v0.6.json.",
  " *",
  " * To change a shape:",
  " *   1. Edit content/schemas/schema_pack_v0.6.json",
  " *   2. Run `npm run gen:types`",
  " *   3. Commit BOTH the schema change AND this regenerated file",
  " *",
  " * CI verifies via `npm run gen:types:check`.",
  " * Hand-edits will be overwritten.",
  " * ============================================================================",
  " */",
  "",
  "/* eslint-disable */",
  "// prettier-ignore",
  "",
  "",
].join("\n");

function buildCompositeSchema(pack) {
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "FirstPerceptionSchemaPack",
    $defs: pack.$defs || {},
    type: "object",
    description: "Composite — emits one interface per entity. Per-entity aliases at bottom.",
    properties: pack.schemas || {},
    additionalProperties: false,
  };
}

function stripCodexAnnotations(node) {
  if (Array.isArray(node)) { node.forEach(stripCodexAnnotations); return; }
  if (node && typeof node === "object") {
    for (const key of Object.keys(node)) {
      if (key.startsWith("x_")) delete node[key];
      else stripCodexAnnotations(node[key]);
    }
  }
}

function titleCase(key) {
  return key.split("_").map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

async function main() {
  const raw = readFileSync(SCHEMA_PATH, "utf8");
  const pack = JSON.parse(raw);
  stripCodexAnnotations(pack);

  const composite = buildCompositeSchema(pack);
  const compiled = await compile(composite, "FirstPerceptionSchemaPack", {
    bannerComment: "",
    additionalProperties: false,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    strictIndexSignatures: false,
    style: { semi: true, singleQuote: false },
  });

  const aliasLines = Object.keys(pack.schemas || {}).map(k => {
    const tc = titleCase(k);
    return 'export type ' + tc + 'Schema = NonNullable<FirstPerceptionSchemaPack["' + k + '"]>;';
  });

  const meta = [
    "",
    "",
    "// ============================================================================",
    "// Per-entity type aliases — ergonomic exports.",
    "// Suffix \"Schema\" avoids collisions with runtime types in index.ts.",
    "// ============================================================================",
    "",
    aliasLines.join("\n"),
    "",
    "",
    "// ============================================================================",
    "// Generated from schema_pack v" + (pack.version || "unknown"),
    "// Entity count: " + Object.keys(pack.schemas || {}).length,
    "// $defs count:  " + Object.keys(pack.$defs || {}).length,
    "// Source: content/schemas/schema_pack_v0.6.json",
    "// ============================================================================",
    "",
  ].join("\n");

  const output = BANNER + compiled + meta;
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, output, "utf8");

  console.log("✓ generated " + OUT_PATH);
  console.log("  entities: " + Object.keys(pack.schemas || {}).length);
  console.log("  $defs:    " + Object.keys(pack.$defs || {}).length);
  console.log("  bytes:    " + output.length);
}

main().catch(err => { console.error("FATAL:", err); process.exit(1); });
