#!/usr/bin/env node
/**
 * generate-zod.mjs — Generate Zod runtime validators from schema_pack_vX.X.json
 *
 * Reads:   content/schemas/schema_pack_vX.X.json (auto-detects latest version)
 * Writes:  packages/types/src/zod-validators.ts
 *
 * Per ARD-009: schema_pack canonical; Zod validators are a DERIVED ARTIFACT.
 * Per ARD-011: JSONB columns get matching Zod schemas for runtime validation on writes.
 *
 * Design decisions:
 *   - One Zod schema per $def + top-level entity
 *   - Discriminated union for oneOf with x_discriminator
 *   - Range bounds emitted as .min().max()
 *   - Optional handling: .optional() for non-required fields
 *   - F1 (pending Phase 4a.5): nullable-enum → .nullable()
 *   - F2 (pending Phase 4a.5): const → z.literal(value)
 *
 * Hand-edits will be overwritten.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SCHEMAS_DIR = resolve(ROOT, "content/schemas");
const OUT_PATH = resolve(ROOT, "packages/types/src/zod-validators.ts");

const BANNER = (version, srcFile) => `/**
 * ============================================================================
 * AUTO-GENERATED — DO NOT EDIT
 * ============================================================================
 * Generated by scripts/generate-zod.mjs from content/schemas/${srcFile}.
 * Per ARD-009: schema_pack is canonical; this file is a DERIVED ARTIFACT.
 *
 * Schema version: ${version}
 * Generated at:   ${new Date().toISOString()}
 *
 * To change validators:
 *   1. Edit content/schemas/${srcFile}
 *   2. Run \`npm run gen:zod\`
 *   3. Commit BOTH the schema change AND this regenerated file
 *
 * CI verifies via \`npm run gen:check\`.
 * Hand-edits will be overwritten.
 * ============================================================================
 */

/* eslint-disable */
// prettier-ignore

import { z } from "zod";

`;

function findLatestSchemaPack() {
  const files = readdirSync(SCHEMAS_DIR).filter(f => /^schema_pack_v\d+\.\d+\.json$/.test(f)).sort();
  if (files.length === 0) throw new Error(`No schema_pack found in ${SCHEMAS_DIR}`);
  return files[files.length - 1];
}

function titleCase(key) {
  return key.split("_").map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

function renderZod(node, defRegistry, depth = 0) {
  if (!node || typeof node !== "object") return "z.unknown()";
  if (node.$ref) {
    const refName = node.$ref.replace(/^#\/\$defs\//, "");
    return `${titleCase(refName)}Z`;
  }
  if (node.const !== undefined) {
    return `z.literal(${JSON.stringify(node.const)})`;
  }
  if (node.enum && Array.isArray(node.enum) && Array.isArray(node.type) && node.type.includes("null")) {
    return `z.enum([${node.enum.filter(v => v !== null).map(v => JSON.stringify(v)).join(", ")}]).nullable()`;
  }
  if (node.enum && Array.isArray(node.enum)) {
    return `z.enum([${node.enum.map(v => JSON.stringify(v)).join(", ")}])`;
  }
  if (node.oneOf && Array.isArray(node.oneOf) && node.x_discriminator) {
    const variants = node.oneOf.map(v => renderZod(v, defRegistry, depth + 1));
    return `z.discriminatedUnion(${JSON.stringify(node.x_discriminator)}, [${variants.join(", ")}])`;
  }
  if (node.oneOf && Array.isArray(node.oneOf)) {
    const variants = node.oneOf.map(v => renderZod(v, defRegistry, depth + 1));
    return `z.union([${variants.join(", ")}])`;
  }
  if (node.anyOf && Array.isArray(node.anyOf)) {
    const variants = node.anyOf.map(v => renderZod(v, defRegistry, depth + 1));
    return `z.union([${variants.join(", ")}])`;
  }
  const t = node.type;
  if (t === "string") {
    let expr = "z.string()";
    if (node.format === "date-time") expr = "z.string().datetime()";
    if (node.minLength != null) expr += `.min(${node.minLength})`;
    if (node.maxLength != null) expr += `.max(${node.maxLength})`;
    if (node.pattern) expr += `.regex(${JSON.stringify(node.pattern)})`;
    return expr;
  }
  if (t === "integer" || t === "number") {
    let expr = t === "integer" ? "z.number().int()" : "z.number()";
    if (node.minimum != null) expr += `.min(${node.minimum})`;
    if (node.maximum != null) expr += `.max(${node.maximum})`;
    return expr;
  }
  if (t === "boolean") return "z.boolean()";
  if (t === "null") return "z.null()";
  if (t === "array") {
    const itemSchema = node.items ? renderZod(node.items, defRegistry, depth + 1) : "z.unknown()";
    let expr = `z.array(${itemSchema})`;
    if (node.minItems != null) expr += `.min(${node.minItems})`;
    if (node.maxItems != null) expr += `.max(${node.maxItems})`;
    return expr;
  }
  if (t === "object" || node.properties) {
    const props = node.properties || {};
    const required = new Set(node.required || []);
    const lines = ["z.object({"];
    for (const [k, v] of Object.entries(props)) {
      const expr = renderZod(v, defRegistry, depth + 1);
      const opt = required.has(k) ? "" : ".optional()";
      lines.push(`    ${JSON.stringify(k)}: ${expr}${opt},`);
    }
    lines.push("  })");
    let expr = lines.join("\n  ");
    if (node.additionalProperties === false) expr += ".strict()";
    else if (typeof node.additionalProperties === "object") {
      const catchExpr = renderZod(node.additionalProperties, defRegistry, depth + 1);
      expr += `.catchall(${catchExpr})`;
    }
    return expr;
  }
  if (Array.isArray(t)) {
    if (t.includes("null") && t.length === 2) {
      const other = t.find(x => x !== "null");
      const inner = renderZod({ ...node, type: other }, defRegistry, depth + 1);
      return `${inner}.nullable()`;
    }
    const variants = t.map(typeName => renderZod({ ...node, type: typeName }, defRegistry, depth + 1));
    return `z.union([${variants.join(", ")}])`;
  }
  return "z.unknown()";
}

function stripCodexAnnotations(node) {
  if (Array.isArray(node)) { node.forEach(stripCodexAnnotations); return; }
  if (node && typeof node === "object") {
    for (const key of Object.keys(node)) {
      if (key.startsWith("x_") && key !== "x_discriminator") delete node[key];
      else stripCodexAnnotations(node[key]);
    }
  }
}

async function main() {
  const srcFile = findLatestSchemaPack();
  const srcPath = resolve(SCHEMAS_DIR, srcFile);
  const raw = readFileSync(srcPath, "utf8");
  const pack = JSON.parse(raw);
  stripCodexAnnotations(pack);
  const version = pack.version || "unknown";
  const defs = pack.$defs || {};
  const schemas = pack.schemas || {};
  const out = [];
  out.push(BANNER(version, srcFile));
  const defRegistry = new Set([...Object.keys(defs), ...Object.keys(schemas)]);
  out.push("// ============================================================================");
  out.push(`// $defs (${Object.keys(defs).length})`);
  out.push("// ============================================================================");
  out.push("");
  for (const [defName, defNode] of Object.entries(defs)) {
    const exprName = `${titleCase(defName)}Z`;
    const expr = renderZod(defNode, defRegistry);
    out.push(`export const ${exprName} = ${expr};`);
    out.push(`export type ${titleCase(defName)} = z.infer<typeof ${exprName}>;`);
    out.push("");
  }
  out.push("// ============================================================================");
  out.push(`// Top-level entities (${Object.keys(schemas).length})`);
  out.push("// ============================================================================");
  out.push("");
  for (const [entityName, entityNode] of Object.entries(schemas)) {
    const exprName = `${titleCase(entityName)}SchemaZ`;
    const expr = renderZod(entityNode, defRegistry);
    out.push(`export const ${exprName} = ${expr};`);
    out.push(`export type ${titleCase(entityName)}Schema = z.infer<typeof ${exprName}>;`);
    out.push("");
  }
  out.push(`// ${Object.keys(defs).length} $defs · ${Object.keys(schemas).length} entities`);
  out.push(`// END OF GENERATED Zod VALIDATORS`);
  out.push("");
  const ts = out.join("\n");
  writeFileSync(OUT_PATH, ts);
  console.log(`generate-zod.mjs: wrote ${OUT_PATH} (${ts.length} bytes; ${Object.keys(defs).length} defs; ${Object.keys(schemas).length} entities)`);
}

main().catch((err) => {
  console.error("generate-zod.mjs FAILED:", err);
  process.exit(1);
});
