#!/usr/bin/env node
/**
 * generate-ddl.mjs — Generate Postgres DDL from schema_pack_vX.X.json
 *
 * Reads:   content/schemas/schema_pack_vX.X.json (auto-detects latest version)
 * Writes:  database/schema.postgres.generated.sql
 *
 * Per ARD-009: schema_pack is canonical; Postgres DDL is a DERIVED ARTIFACT.
 * Per ARD-010: 5 schemas (public / content / state / behavior / engine).
 * Per ARD-011: FK enforcement; native ENUM vs lookup table; JSONB CHECK;
 *              polymorphic ownership REJECTED.
 * Per ARD-012: RLS enabled per table; service-role baseline policy.
 * Per ARD-016: schema_version column for dual-write transition.
 *
 * Extension fields read from schema_pack (Session 4 authors set these):
 *   x_schema_namespace: "public" | "content" | "state" | "behavior" | "engine"
 *   x_enum_strategy: "native" | "lookup"
 *   x_indexes: [{ columns: string[], where?: string, kind?: "btree"|"gin"|"hash" }]
 *   x_fk_policy: { on_delete: "RESTRICT" | "CASCADE" | "SET NULL" | "NO ACTION" }
 *   x_polymorphic_holder: { kinds: string[] }  // explodes to per-type FK columns
 *
 * Hand-authored migration files (per ARD-009) handle:
 *   - RLS policies (supabase/migrations/*_rls_*.sql)
 *   - Realtime publications (supabase/migrations/*_realtime_publications.sql)
 *   - Storage bucket policies
 *
 * This generator produces only:
 *   - CREATE SCHEMA statements
 *   - CREATE TYPE ... AS ENUM statements
 *   - CREATE TABLE statements (with FK + CHECK constraints)
 *   - CREATE INDEX statements
 *   - ALTER TABLE ... ENABLE ROW LEVEL SECURITY (RLS is enabled per table; policies are separate)
 *   - Header comment with version + generation timestamp
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SCHEMAS_DIR = resolve(ROOT, "content/schemas");
const OUT_PATH = resolve(ROOT, "database/schema.postgres.generated.sql");

const NAMESPACES = ["public", "content", "state", "behavior", "engine"];
const DEFAULT_NAMESPACE = "public";

const BANNER = (version, srcFile) => `-- ============================================================================
-- AUTO-GENERATED — DO NOT EDIT
-- ============================================================================
-- Generated by scripts/generate-ddl.mjs from content/schemas/${srcFile}.
-- Per ARD-009: schema_pack is canonical; this file is a DERIVED ARTIFACT.
--
-- Schema version: ${version}
-- Generated at:   ${new Date().toISOString()}
--
-- To change DDL output:
--   1. Edit content/schemas/${srcFile}
--   2. Run \`npm run gen:ddl\`
--   3. Commit BOTH the schema change AND this regenerated file
--
-- Hand-authored migrations (NOT in this file):
--   - RLS policies — supabase/migrations/<ts>_rls_*.sql
--   - Realtime publications — supabase/migrations/<ts>_realtime_publications.sql
--   - Storage bucket policies — supabase/migrations/<ts>_storage_policies.sql
--   - Edge Function definitions — supabase/functions/<name>/index.ts
--
-- CI verifies via \`npm run gen:check\`.
-- Hand-edits will be overwritten.
-- ============================================================================

`;

// -----------------------------------------------------------------------------
// Schema pack discovery
// -----------------------------------------------------------------------------

function findLatestSchemaPack() {
  const files = readdirSync(SCHEMAS_DIR)
    .filter(f => /^schema_pack_v\d+\.\d+\.json$/.test(f))
    .sort();
  if (files.length === 0) {
    throw new Error(`No schema_pack_vX.X.json found in ${SCHEMAS_DIR}`);
  }
  return files[files.length - 1];
}

// -----------------------------------------------------------------------------
// SQL helpers
// -----------------------------------------------------------------------------

function quote(name) {
  // Simple identifier quoting (avoids reserved words)
  return `"${name}"`;
}

function snakeCase(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
}

function sqlTypeForJsonSchema(node, hint = {}) {
  if (!node || typeof node !== "object") return "TEXT";
  if (node.$ref) return "TEXT"; // FKs handled separately
  if (node.enum && Array.isArray(node.enum) && hint.x_enum_strategy === "native") {
    return quote(hint.enum_type_name || "unknown_enum");
  }
  const t = node.type;
  if (t === "string") {
    if (node.format === "date-time") return "TIMESTAMPTZ";
    if (node.format === "date") return "DATE";
    return "TEXT";
  }
  if (t === "integer") {
    if (node.minimum != null && node.maximum != null) {
      // Use SMALLINT for small bounded ranges to save space
      if (node.maximum < 32768 && node.minimum > -32768) return "SMALLINT";
    }
    return "INTEGER";
  }
  if (t === "number") return "NUMERIC";
  if (t === "boolean") return "BOOLEAN";
  if (t === "array") return "JSONB"; // arrays stored as JSONB by default; can be exploded to join tables via x_normalize
  if (t === "object") return "JSONB";
  // Union types or unknown
  if (Array.isArray(t)) {
    if (t.includes("null")) {
      // nullable; type is the non-null one
      const nonNull = t.find(x => x !== "null");
      return sqlTypeForJsonSchema({ ...node, type: nonNull }, hint);
    }
  }
  return "TEXT";
}

// -----------------------------------------------------------------------------
// ENUM extraction
// -----------------------------------------------------------------------------

function extractEnums(pack) {
  const enums = []; // { name, values, namespace, strategy }
  const seen = new Set();

  function visit(node, path) {
    if (Array.isArray(node)) { node.forEach((n, i) => visit(n, [...path, i])); return; }
    if (node && typeof node === "object") {
      // Phase 4a.5 / Khoja Decision #3 (LOCKED): default native UNLESS x_enum_strategy
      // explicitly says "lookup". Unannotated enum arrays become native Postgres ENUM
      // types automatically. This implements the locked rule without requiring 143
      // manual sweep edits on v0.7-inherited enums.
      if (node.enum && Array.isArray(node.enum)) {
        const strategy = node.x_enum_strategy === "lookup" ? "lookup" : "native";
        // Skip enums embedded in oneOf variants — those are discriminators, not enums per se
        const lastKey = path[path.length - 1];
        if (lastKey === "const") return;
        const name = node.x_enum_name || node.x_lookup_table_name ||
          snakeCase(path.filter(p => typeof p === "string").join("_") + "_enum");
        if (!seen.has(name)) {
          enums.push({
            name,
            values: node.enum.filter(v => v !== null && v !== undefined),
            namespace: node.x_schema_namespace ||
              (strategy === "lookup" ? "content" : DEFAULT_NAMESPACE),
            strategy,
          });
          seen.add(name);
        }
      }
      for (const key of Object.keys(node)) {
        if (!key.startsWith("x_")) visit(node[key], [...path, key]);
      }
    }
  }
  visit(pack.$defs || {}, ["defs"]);
  visit(pack.schemas || {}, ["schemas"]);
  return enums;
}

// F6 — Lookup-table emission. Per Khoja Decision #3 locked criteria.
// Lookup tables carry metadata columns (label, description, source_pack,
// sort_order, ui_glyph, localization_key, is_active, is_deprecated,
// deprecation_note) that native ENUMs cannot. Per-row seed data lands at
// Session 6 = Phase 24d.
function emitLookupTable(e) {
  const lines = [];
  lines.push(`-- ${e.namespace}.enum_${e.name} (lookup table — content-data-like enum per Khoja Decision #3)`);
  lines.push(`CREATE TABLE IF NOT EXISTS ${quote(e.namespace)}.${quote("enum_" + e.name)} (`);
  lines.push(`  "id" TEXT PRIMARY KEY,`);
  lines.push(`  "label" TEXT NOT NULL,`);
  lines.push(`  "description" TEXT,`);
  lines.push(`  "source_pack" TEXT,`);
  lines.push(`  "sort_order" INTEGER,`);
  lines.push(`  "ui_glyph" TEXT,`);
  lines.push(`  "localization_key" TEXT,`);
  lines.push(`  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,`);
  lines.push(`  "is_deprecated" BOOLEAN NOT NULL DEFAULT FALSE,`);
  lines.push(`  "deprecation_note" TEXT,`);
  lines.push(`  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
  lines.push(`  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  lines.push(`);`);
  lines.push(`ALTER TABLE ${quote(e.namespace)}.${quote("enum_" + e.name)} ENABLE ROW LEVEL SECURITY;`);
  // Seed default value set (engine has default value mapping; can be edited)
  if (e.values.length > 0) {
    lines.push(`-- Default value set (Session 6 seed may extend / refine):`);
    for (const v of e.values) {
      const id = String(v).replace(/'/g, "''");
      lines.push(`INSERT INTO ${quote(e.namespace)}.${quote("enum_" + e.name)} (id, label) VALUES ('${id}', '${id}') ON CONFLICT DO NOTHING;`);
    }
  }
  lines.push(``);
  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// Schema-pack analysis: which entities become tables?
// -----------------------------------------------------------------------------

function entitiesToEmit(pack) {
  const entities = [];
  for (const [name, def] of Object.entries(pack.schemas || {})) {
    const ns = def.x_schema_namespace || DEFAULT_NAMESPACE;
    entities.push({
      name: snakeCase(name),
      original_name: name,
      def,
      namespace: ns,
      indexes: def.x_indexes || [],
    });
  }
  return entities;
}

// -----------------------------------------------------------------------------
// F5 — FK inference from naming convention
// Per FOUNDATION_STABILITY_AUDIT: `<entity>_id` IMPLIES FK when target entity exists.
// Default `on_delete` policy by target namespace per ARD-011 §1.
// -----------------------------------------------------------------------------

function buildEntityNameIndex(pack) {
  // Returns map: entity_name → { namespace, pk_column }
  const idx = {};
  for (const [name, def] of Object.entries(pack.schemas || {})) {
    const ns = def.x_schema_namespace || DEFAULT_NAMESPACE;
    const props = def.properties || {};
    const required = def.required || [];
    // Determine PK column:
    //  1. prefer `<entity>_id`
    //  2. fallback to bare `id`
    //  3. fallback to first required field ending in `_id` (convention: PK is first required)
    let pk = `${name.toLowerCase()}_id`;
    if (!props[pk]) pk = "id";
    if (!props[pk]) {
      const firstRequiredId = required.find(r => r.endsWith("_id") && props[r]);
      if (firstRequiredId) pk = firstRequiredId;
    }
    idx[name.toLowerCase()] = { namespace: ns, pk_column: pk, tableName: snakeCase(name) };
  }
  return idx;
}

function defaultFkPolicyForNamespace(targetNs) {
  // Per ARD-011 §1:
  //   References INTO content.* → RESTRICT
  //   References INTO state.*   → CASCADE (same-session ownership)
  //   References INTO public.*  → RESTRICT (preserves existing 9 tables)
  //   Otherwise                  → SET NULL
  if (targetNs === "content") return "RESTRICT";
  if (targetNs === "state") return "CASCADE";
  if (targetNs === "public") return "RESTRICT";
  return "SET NULL";
}

function inferFkTarget(colName, currentEntityName, entityIndex) {
  // If column is named `<entity>_id` and `<entity>` exists in schema_pack,
  // infer the FK target. Returns null if no match.
  if (!colName.endsWith("_id")) return null;
  if (colName === "id") return null;
  const candidateEntityName = colName.slice(0, -3); // strip "_id"
  // skip self-reference (PK column)
  if (candidateEntityName === currentEntityName.toLowerCase()) return null;
  const entry = entityIndex[candidateEntityName];
  if (!entry) return null;
  return {
    targetEntity: candidateEntityName,
    namespace: entry.namespace,
    tableName: entry.tableName,
    pkColumn: entry.pk_column,
    onDelete: defaultFkPolicyForNamespace(entry.namespace),
  };
}

// -----------------------------------------------------------------------------
// CREATE TABLE emission
// -----------------------------------------------------------------------------

function emitTable(entity, allEnums, entityIndex, fkOut) {
  const { name, def, namespace } = entity;
  const cols = [];
  const constraints = [];
  const props = def.properties || {};
  const required = new Set(def.required || []);
  // Resolve PK column the same way buildEntityNameIndex does (so emit + index agree).
  const pkCandidate = entityIndex?.[entity.original_name.toLowerCase()]?.pk_column;

  // Phase 6a.5.6: composite-PK support via x_composite_primary_key annotation.
  // When set (array of column names), suppress inline PRIMARY KEY on the single
  // inferred column + emit table-level PRIMARY KEY (col1, col2, ...) constraint.
  // Backward-compat: entities without the annotation get default single-PK behavior.
  const compositePkRaw = def.x_composite_primary_key;
  const compositePkCols = Array.isArray(compositePkRaw)
    ? compositePkRaw.map((c) => snakeCase(c))
    : null;
  const hasCompositePk = compositePkCols !== null && compositePkCols.length > 1;

  for (const [colName, colDef] of Object.entries(props)) {
    const col = snakeCase(colName);
    // Skip $defs references at column level for now (would need denormalization decision)
    if (colDef.$ref && !colDef.x_inline) {
      // Treat as JSONB referencing the $def shape
      const nullable = !required.has(colName);
      cols.push(`  ${quote(col)} JSONB${nullable ? "" : " NOT NULL"}`);
      // CHECK constraint via pg_jsonschema (if available) — emit as block comment
      // (must be /* */ not -- to avoid swallowing the trailing comma added on join)
      cols[cols.length - 1] += `  /* $ref: ${colDef.$ref} */`;
      continue;
    }
    // Inline PRIMARY KEY suppressed when composite PK is declared at table level.
    const isPrimaryKey = !hasCompositePk && (
      (pkCandidate && col === pkCandidate)
      || colName === "id"
      || (colName.endsWith("_id") && colName === `${entity.original_name.toLowerCase()}_id`)
    );
    // FK column heuristic: under composite PK, the entity_id column is still
    // a FK target candidate (FKs into template, etc.) — treat as FK if it's
    // not in the composite-PK set's leading column AND it ends with _id.
    const isFk = colName.endsWith("_id") && !isPrimaryKey;

    // ENUM detection
    let sqlType;
    if (colDef.enum && colDef.x_enum_strategy === "native") {
      const enumName = colDef.x_enum_name || `${name}_${col}_enum`;
      // F-ENUM-NS: enum types live in the SAME namespace they were CREATEd in (extractEnums
      // defaults to public). Column-site references must match. Always public for v0.8 native enums.
      const enumNs = colDef.x_schema_namespace || (allEnums?.find(e => e.name === enumName)?.namespace) || "public";
      sqlType = `${quote(enumNs)}.${quote(enumName)}`;
    } else {
      sqlType = sqlTypeForJsonSchema(colDef, {});
    }

    const nullable = !required.has(colName) ? "" : " NOT NULL";
    const pk = isPrimaryKey ? " PRIMARY KEY" : "";
    let colLine = `  ${quote(col)} ${sqlType}${pk}${nullable}`;

    // FK constraint — F5: prefer x_fk_target if explicit, else infer from naming
    let fkResolution = null;
    if (isFk) {
      if (colDef.x_fk_target) {
        // Explicit annotation (highest priority)
        const fkPolicy = colDef.x_fk_policy?.on_delete || "RESTRICT";
        let fkNs, fkTable;
        if (colDef.x_fk_target.includes(".")) {
          [fkNs, fkTable] = colDef.x_fk_target.split(".");
        } else {
          // F-FK-NS: unqualified target — look up target's actual namespace, NOT source's.
          fkTable = colDef.x_fk_target;
          const targetEntry = entityIndex?.[fkTable.toLowerCase()];
          fkNs = targetEntry?.namespace || namespace; // namespace fallback only if unknown
        }
        // F-FK-PK: pkColumn from entityIndex (proper PK), fallback to "id".
        const targetEntry = entityIndex?.[fkTable.toLowerCase()];
        const fkPk = targetEntry?.pk_column || "id";
        fkResolution = { namespace: fkNs, tableName: fkTable, pkColumn: fkPk, onDelete: fkPolicy, source: "explicit" };
      } else if (entityIndex) {
        // F5: infer from `<entity>_id` naming convention
        const inferred = inferFkTarget(colName, entity.original_name, entityIndex);
        if (inferred) {
          fkResolution = { ...inferred, source: "inferred" };
        }
      }
    }
    if (fkResolution) {
      const constraintName = `fk_${entity.name}_${col}`;
      // F-FK-ORDER: emit FK as separate ALTER TABLE at end of file (after all CREATE TABLEs)
      // to avoid forward-reference errors when an entity references a not-yet-created table.
      if (fkOut) {
        fkOut.push({
          tableNs: namespace,
          tableName: name,
          constraintName,
          column: col,
          refNs: fkResolution.namespace,
          refTable: fkResolution.tableName,
          refColumn: fkResolution.pkColumn,
          onDelete: fkResolution.onDelete,
          source: fkResolution.source,
        });
      } else {
        // Fallback path (kept for safety; not used in main()).
        constraints.push(
          `  CONSTRAINT ${quote(constraintName)} FOREIGN KEY (${quote(col)}) REFERENCES ${quote(fkResolution.namespace)}.${quote(fkResolution.tableName)}(${quote(fkResolution.pkColumn)}) ON DELETE ${fkResolution.onDelete}` +
          (fkResolution.source === "inferred" ? "  /* F5: inferred from naming convention */" : "")
        );
      }
    }

    // Range constraints (only on numeric column types — TEXT/JSONB/BOOLEAN skip)
    // F-RANGE-NUMERIC: schema_pack may carry minimum/maximum on non-numeric fields
    // (legacy v0.7 artifact); only emit CHECK when the underlying SQL type is numeric.
    const isNumericType = /^(INTEGER|SMALLINT|BIGINT|NUMERIC|DOUBLE PRECISION|REAL)$/i.test(sqlType.replace(/"/g, ""));
    if (isNumericType) {
      if (colDef.minimum != null) {
        constraints.push(`  CHECK (${quote(col)} >= ${colDef.minimum})`);
      }
      if (colDef.maximum != null) {
        constraints.push(`  CHECK (${quote(col)} <= ${colDef.maximum})`);
      }
    }

    cols.push(colLine);
  }

  // schema_version column for ARD-016 dual-write phase
  // Skip if entity already declared schema_version itself (v0.7 inherited: litany, marginalia)
  const hasOwnSchemaVersion = Object.keys(props).some(k => snakeCase(k) === "schema_version");
  if ((namespace === "public" || namespace === "state") && !hasOwnSchemaVersion) {
    cols.push(`  "schema_version" TEXT NOT NULL DEFAULT 'v0.8'`);
  }

  // timestamps
  cols.push(`  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  cols.push(`  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()`);

  // Phase 6a.5.6: emit table-level composite PRIMARY KEY when annotated.
  if (hasCompositePk) {
    const pkCols = compositePkCols.map(quote).join(", ");
    constraints.push(`  PRIMARY KEY (${pkCols})`);
  }

  const allLines = [...cols, ...constraints];
  const body = allLines.join(",\n");

  const lines = [];
  lines.push(`-- ${entity.original_name} (${namespace}.${name})`);
  if (def.description) {
    lines.push(`-- ${def.description.replace(/\n/g, "\n-- ")}`);
  }
  lines.push(`CREATE TABLE IF NOT EXISTS ${quote(namespace)}.${quote(name)} (`);
  lines.push(body);
  lines.push(`);`);
  if (def.description) {
    // Postgres string literal: single quotes, with single-quote escape via doubling
    const sqlStr = `'${def.description.replace(/'/g, "''")}'`;
    lines.push(`COMMENT ON TABLE ${quote(namespace)}.${quote(name)} IS ${sqlStr};`);
  }
  lines.push(`ALTER TABLE ${quote(namespace)}.${quote(name)} ENABLE ROW LEVEL SECURITY;`);
  lines.push(``);

  // Indexes
  for (const idx of entity.indexes) {
    const idxName = `idx_${name}_${idx.columns.map(snakeCase).join("_")}`;
    const cols = idx.columns.map(c => `${quote(snakeCase(c))}${idx.directions?.[c] === "DESC" ? " DESC" : ""}`).join(", ");
    const where = idx.where ? ` WHERE ${idx.where}` : "";
    const kind = idx.kind && idx.kind !== "btree" ? ` USING ${idx.kind}` : "";
    lines.push(`CREATE INDEX IF NOT EXISTS ${idxName} ON ${quote(namespace)}.${quote(name)}${kind} (${cols})${where};`);
  }
  if (entity.indexes.length > 0) lines.push(``);

  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// Main
// -----------------------------------------------------------------------------

async function main() {
  const srcFile = findLatestSchemaPack();
  const srcPath = resolve(SCHEMAS_DIR, srcFile);
  const raw = readFileSync(srcPath, "utf8");
  const pack = JSON.parse(raw);
  const version = pack.version || "unknown";

  const out = [];
  out.push(BANNER(version, srcFile));

  // 1. CREATE SCHEMA statements
  out.push(`-- ----------------------------------------------------------------------------`);
  out.push(`-- Schema namespaces (per ARD-010)`);
  out.push(`-- ----------------------------------------------------------------------------`);
  for (const ns of NAMESPACES) {
    out.push(`CREATE SCHEMA IF NOT EXISTS ${quote(ns)};`);
  }
  out.push(``);

  // 2. ENUMs — split into native (CREATE TYPE) and lookup (CREATE TABLE) per Khoja Decision #3
  const enums = extractEnums(pack);
  const nativeEnums = enums.filter(e => e.strategy === "native");
  const lookupEnums = enums.filter(e => e.strategy === "lookup");

  if (nativeEnums.length > 0) {
    out.push(`-- ----------------------------------------------------------------------------`);
    out.push(`-- Native Postgres ENUM types (per ARD-011 §2; Khoja Decision #3 'native' criteria)`);
    out.push(`-- ----------------------------------------------------------------------------`);
    for (const e of nativeEnums) {
      out.push(`-- ${e.namespace}.${e.name}`);
      out.push(`DO $$ BEGIN`);
      out.push(`  CREATE TYPE ${quote(e.namespace)}.${quote(e.name)} AS ENUM (`);
      out.push(`    ${e.values.map(v => `'${String(v).replace(/'/g, "''")}'`).join(",\n    ")}`);
      out.push(`  );`);
      out.push(`EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
      out.push(``);
    }
  }

  if (lookupEnums.length > 0) {
    out.push(`-- ----------------------------------------------------------------------------`);
    out.push(`-- Lookup-table ENUMs (per Khoja Decision #3 'lookup' criteria)`);
    out.push(`-- Content-extensible: regional packs + mod packs add values via INSERT.`);
    out.push(`-- Carries metadata: label, description, source_pack, sort_order, ui_glyph, etc.`);
    out.push(`-- ----------------------------------------------------------------------------`);
    for (const e of lookupEnums) {
      out.push(emitLookupTable(e));
    }
  }

  // 3. Tables per entity
  const entities = entitiesToEmit(pack);
  const entityIndex = buildEntityNameIndex(pack);   // F5: FK inference index
  if (entities.length > 0) {
    // Group by namespace for cleaner output
    const byNs = {};
    for (const e of entities) {
      (byNs[e.namespace] = byNs[e.namespace] || []).push(e);
    }
    const fkOut = []; // collected across all entities; emitted last
    for (const ns of NAMESPACES) {
      const ents = byNs[ns];
      if (!ents || ents.length === 0) continue;
      out.push(`-- ============================================================================`);
      out.push(`-- ${ns.toUpperCase()} schema — ${ents.length} entities`);
      out.push(`-- ============================================================================`);
      for (const e of ents) {
        out.push(emitTable(e, enums, entityIndex, fkOut));
      }
    }

    // 3b. FK constraints emitted LAST (per F-FK-ORDER fix) so all referenced tables exist.
    if (fkOut.length > 0) {
      out.push(`-- ============================================================================`);
      out.push(`-- FK CONSTRAINTS — emitted last to avoid forward-reference errors (F-FK-ORDER)`);
      out.push(`-- ============================================================================`);
      for (const fk of fkOut) {
        const note = fk.source === "inferred" ? "  /* F5: inferred from naming convention */" : "";
        // Wrap in DO block for idempotency (ADD CONSTRAINT has no IF NOT EXISTS variant)
        out.push(`DO $$ BEGIN`);
        out.push(
          `  ALTER TABLE ${quote(fk.tableNs)}.${quote(fk.tableName)} ` +
          `ADD CONSTRAINT ${quote(fk.constraintName)} ` +
          `FOREIGN KEY (${quote(fk.column)}) ` +
          `REFERENCES ${quote(fk.refNs)}.${quote(fk.refTable)}(${quote(fk.refColumn)}) ` +
          `ON DELETE ${fk.onDelete};${note}`
        );
        out.push(`EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
      }
      out.push(``);
    }
  }

  // 4. Footer
  out.push(`-- ----------------------------------------------------------------------------`);
  out.push(`-- END OF GENERATED DDL`);
  out.push(`-- ${entities.length} entities · ${enums.length} enums · ${NAMESPACES.length} schemas`);
  out.push(`-- ----------------------------------------------------------------------------`);

  const sql = out.join("\n");
  writeFileSync(OUT_PATH, sql);
  console.log(`✓ generate-ddl.mjs: wrote ${OUT_PATH} (${sql.length} bytes; ${entities.length} entities; ${enums.length} enums)`);
}

main().catch((err) => {
  console.error("generate-ddl.mjs FAILED:", err);
  process.exit(1);
});
